"""initial revision

Revision ID: 056df032ff77
Revises: 
Create Date: 2023-02-15 12:51:35.368536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056df032ff77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
