"""empty message

Revision ID: 06ee89bb6e74
Revises: bcccbd1149d0
Create Date: 2022-05-02 17:50:29.396791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ee89bb6e74'
down_revision = 'bcccbd1149d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh_incoming_rmas', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wh_incoming_rmas', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wh_incoming_rmas', type_='foreignkey')
    op.drop_column('wh_incoming_rmas', 'warehouse_id')
    # ### end Alembic commands ###
