"""remove note from expediiton

Revision ID: 0bab21f532a2
Revises: b0c72a449477
Create Date: 2022-04-20 11:00:45.047783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bab21f532a2'
down_revision = 'b0c72a449477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expeditions', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expeditions', sa.Column('note', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
