"""remove line3

Revision ID: 1f047eea4703
Revises: 
Create Date: 2022-04-21 17:56:20.359699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f047eea4703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='agent_documents')
    op.drop_index('name', table_name='partner_documents')
    op.drop_column('partners', 'billing_line3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('billing_line3', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('name', 'partner_documents', ['name'], unique=False)
    op.create_index('name', 'agent_documents', ['name'], unique=False)
    # ### end Alembic commands ###
