"""has_serie field included in unique constraint

Revision ID: 22635db7a553
Revises: cbc51be1a965
Create Date: 2021-12-15 15:38:55.217847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22635db7a553'
down_revision = 'cbc51be1a965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'items', type_='unique')
    op.create_unique_constraint('uix_1', 'items', ['mpn', 'manufacturer', 'category', 'model', 'capacity', 'color', 'has_serie'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'items', type_='unique')
    op.create_unique_constraint('uix_1', 'items', ['mpn', 'manufacturer', 'category', 'model', 'capacity', 'color'])
    # ### end Alembic commands ###
