"""add foreign key on accounts table

Revision ID: 2b6d3d46bff9
Revises: d7f5c9a4ee76
Create Date: 2021-12-14 14:44:00.257375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6d3d46bff9'
down_revision = 'd7f5c9a4ee76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_accounts', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'partner_accounts', 'partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partner_accounts', type_='foreignkey')
    op.drop_column('partner_accounts', 'partner_id')
    # ### end Alembic commands ###
