"""initial_revision

Revision ID: 2fc17db415ac
Revises: 
Create Date: 2022-02-22 15:06:10.518340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fc17db415ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advanced_lines', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=True)
    op.alter_column('agent_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('agents', 'fixed_salary',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('agents', 'from_profit',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('agents', 'from_turnover',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('agents', 'fixed_perpiece',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('partner_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('purchase_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('sale_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('purchase_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('partner_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('agents', 'fixed_perpiece',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('agents', 'from_turnover',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('agents', 'from_profit',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('agents', 'fixed_salary',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('agent_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('advanced_lines', 'price',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###
