"""initial revision

Revision ID: 3696b846b8be
Revises: 
Create Date: 2022-02-23 09:31:18.366646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3696b846b8be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advanced_lines', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('agent_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('agents', 'fixed_salary',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('agents', 'from_profit',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('agents', 'from_turnover',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('agents', 'fixed_perpiece',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.add_column('expedition_lines', sa.Column('showing_condition', sa.String(length=50), nullable=True))
    op.alter_column('expedition_lines', 'item_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('expedition_lines', 'condition',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('expedition_lines', 'spec',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('expedition_lines', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('imeis', 'warehouse_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('imeis_mask', 'condition',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('imeis_mask', 'spec',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('imeis_mask', 'warehouse_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('partner_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('purchase_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('purchase_proforma_lines', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('purchase_proformas', 'credit_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('reception_lines', 'condition',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('reception_lines', 'spec',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('reception_lines', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('sale_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('sale_expenses', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('sale_payments', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('sale_proforma_lines', 'mix_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('sale_proforma_lines', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('sale_proforma_lines', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               nullable=False)
    op.alter_column('sale_proforma_lines', 'tax',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_proforma_lines', 'tax',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('sale_proforma_lines', 'price',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=mysql.DECIMAL(precision=10, scale=6),
               nullable=True)
    op.alter_column('sale_proforma_lines', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('sale_proforma_lines', 'mix_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('sale_payments', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('sale_expenses', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('sale_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('reception_lines', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('reception_lines', 'spec',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('reception_lines', 'condition',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('purchase_proformas', 'credit_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('purchase_proforma_lines', 'price',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('purchase_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('partner_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('imeis_mask', 'warehouse_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('imeis_mask', 'spec',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('imeis_mask', 'condition',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('imeis', 'warehouse_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('expedition_lines', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('expedition_lines', 'spec',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('expedition_lines', 'condition',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('expedition_lines', 'item_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('expedition_lines', 'showing_condition')
    op.alter_column('agents', 'fixed_perpiece',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('agents', 'from_turnover',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('agents', 'from_profit',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('agents', 'fixed_salary',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('agent_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('advanced_lines', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
