"""currecncy field added to accounts

Revision ID: 3f203cdcda83
Revises: 22635db7a553
Create Date: 2021-12-16 10:33:09.309433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f203cdcda83'
down_revision = '22635db7a553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_accounts', sa.Column('currency', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_accounts', 'currency')
    # ### end Alembic commands ###
