"""empty message

Revision ID: 407501cb5d22
Revises: 
Create Date: 2022-07-29 12:20:19.614847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407501cb5d22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_invoices', sa.Column('external_document', sa.String(length=50), nullable=True))
    op.add_column('purchase_invoices', sa.Column('note', sa.String(length=255), nullable=True))
    op.add_column('sale_invoices', sa.Column('external_document', sa.String(length=50), nullable=True))
    op.add_column('sale_invoices', sa.Column('note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_invoices', 'note')
    op.drop_column('sale_invoices', 'external_document')
    op.drop_column('purchase_invoices', 'note')
    op.drop_column('purchase_invoices', 'external_document')
    # ### end Alembic commands ###
