"""empty message

Revision ID: 4a3af850808e
Revises: e5872fa1f37e
Create Date: 2022-05-02 16:14:15.332795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3af850808e'
down_revision = 'e5872fa1f37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh_incoming_rmas', sa.Column('inventoried', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wh_incoming_rmas', 'inventoried')
    # ### end Alembic commands ###
