"""empty message

Revision ID: 527860042c90
Revises: 2f8fe4054eb5
Create Date: 2022-04-22 17:07:38.196645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527860042c90'
down_revision = '2f8fe4054eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incoming_rma_lines', 'purchase_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('purchase_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
