"""empty message

Revision ID: 651f3fff481b
Revises: 819525d44eb2
Create Date: 2022-05-04 09:27:45.730167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '651f3fff481b'
down_revision = '819525d44eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('recpt', sa.DateTime(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('wtyendsupp', sa.Date(), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('purchas', sa.String(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('defas', sa.String(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('soldas', sa.String(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('public', sa.String(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('saledate', sa.Date(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('exped', sa.DateTime(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('wtyendcust', sa.Date(), nullable=True))
    op.drop_column('incoming_rma_lines', 'defined_as')
    op.drop_column('incoming_rma_lines', 'reception_datetime')
    op.drop_column('incoming_rma_lines', 'purchased_as')
    op.drop_column('incoming_rma_lines', 'warranty_end_sup')
    op.drop_column('incoming_rma_lines', 'sale_date')
    op.drop_column('incoming_rma_lines', 'public_condition')
    op.drop_column('incoming_rma_lines', 'expedition_datetime')
    op.drop_column('incoming_rma_lines', 'sold_as')
    op.drop_column('incoming_rma_lines', 'warranty_end_cust')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('warranty_end_cust', sa.DATE(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('sold_as', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('expedition_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('public_condition', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('sale_date', sa.DATE(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('warranty_end_sup', sa.DATE(), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('purchased_as', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('reception_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('defined_as', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('incoming_rma_lines', 'wtyendcust')
    op.drop_column('incoming_rma_lines', 'exped')
    op.drop_column('incoming_rma_lines', 'saledate')
    op.drop_column('incoming_rma_lines', 'public')
    op.drop_column('incoming_rma_lines', 'soldas')
    op.drop_column('incoming_rma_lines', 'defas')
    op.drop_column('incoming_rma_lines', 'purchas')
    op.drop_column('incoming_rma_lines', 'wtyendsupp')
    op.drop_column('incoming_rma_lines', 'recpt')
    # ### end Alembic commands ###
