"""empty message

Revision ID: 6948193cc381
Revises: 
Create Date: 2023-02-09 15:28:51.385037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6948193cc381'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advanced_lines', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.drop_constraint('advanced_lines_ibfk_3', 'advanced_lines', type_='foreignkey')
    op.drop_column('advanced_lines', 'company_id')
    op.drop_constraint('advanced_lines_definition_ibfk_3', 'advanced_lines_definition', type_='foreignkey')
    op.drop_column('advanced_lines_definition', 'company_id')
    op.alter_column('agent_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.drop_constraint('agent_documents_ibfk_2', 'agent_documents', type_='foreignkey')
    op.drop_column('agent_documents', 'company_id')
    op.alter_column('agents', 'fixed_salary',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.alter_column('agents', 'from_profit',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.alter_column('agents', 'from_turnover',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.alter_column('agents', 'fixed_perpiece',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('agents_ibfk_1', 'agents', type_='foreignkey')
    op.drop_column('agents', 'company_id')
    op.drop_constraint('condition_changes_ibfk_1', 'condition_changes', type_='foreignkey')
    op.drop_column('condition_changes', 'company_id')
    op.drop_constraint('conditions_ibfk_1', 'conditions', type_='foreignkey')
    op.drop_column('conditions', 'company_id')
    op.drop_constraint('couriers_ibfk_1', 'couriers', type_='foreignkey')
    op.drop_column('couriers', 'company_id')
    op.alter_column('credit_note_lines', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('credit_note_lines_ibfk_4', 'credit_note_lines', type_='foreignkey')
    op.drop_column('credit_note_lines', 'company_id')
    op.drop_constraint('expedition_lines_ibfk_3', 'expedition_lines', type_='foreignkey')
    op.drop_column('expedition_lines', 'company_id')
    op.drop_constraint('expedition_series_ibfk_2', 'expedition_series', type_='foreignkey')
    op.drop_column('expedition_series', 'company_id')
    op.drop_constraint('expeditions_ibfk_2', 'expeditions', type_='foreignkey')
    op.drop_column('expeditions', 'company_id')
    op.drop_constraint('imeis_ibfk_3', 'imeis', type_='foreignkey')
    op.drop_column('imeis', 'company_id')
    op.drop_constraint('imeis_mask_ibfk_3', 'imeis_mask', type_='foreignkey')
    op.drop_column('imeis_mask', 'company_id')
    op.alter_column('incoming_rma_lines', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('incoming_rma_lines_ibfk_3', 'incoming_rma_lines', type_='foreignkey')
    op.drop_column('incoming_rma_lines', 'company_id')
    op.drop_constraint('incoming_rmas_ibfk_1', 'incoming_rmas', type_='foreignkey')
    op.drop_column('incoming_rmas', 'company_id')
    op.drop_constraint('items_ibfk_1', 'items', type_='foreignkey')
    op.drop_column('items', 'company_id')
    op.drop_constraint('many_manies_ibfk_3', 'many_manies', type_='foreignkey')
    op.drop_column('many_manies', 'company_id')
    op.drop_constraint('partner_accounts_ibfk_2', 'partner_accounts', type_='foreignkey')
    op.drop_column('partner_accounts', 'company_id')
    op.drop_constraint('partner_contacts_ibfk_2', 'partner_contacts', type_='foreignkey')
    op.drop_column('partner_contacts', 'company_id')
    op.alter_column('partner_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.drop_constraint('partner_documents_ibfk_2', 'partner_documents', type_='foreignkey')
    op.drop_column('partner_documents', 'company_id')
    op.alter_column('partners', 'amount_credit_limit',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.drop_constraint('partners_ibfk_2', 'partners', type_='foreignkey')
    op.drop_column('partners', 'company_id')
    op.alter_column('purchase_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.drop_constraint('purchase_documents_ibfk_2', 'purchase_documents', type_='foreignkey')
    op.drop_column('purchase_documents', 'company_id')
    op.alter_column('purchase_expenses', 'amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.drop_constraint('purchase_expenses_ibfk_2', 'purchase_expenses', type_='foreignkey')
    op.drop_column('purchase_expenses', 'company_id')
    op.drop_constraint('purchase_invoices_ibfk_1', 'purchase_invoices', type_='foreignkey')
    op.drop_column('purchase_invoices', 'company_id')
    op.alter_column('purchase_payments', 'amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.alter_column('purchase_payments', 'rate',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('purchase_payments_ibfk_2', 'purchase_payments', type_='foreignkey')
    op.drop_column('purchase_payments', 'company_id')
    op.alter_column('purchase_proforma_lines', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('purchase_proforma_lines_ibfk_3', 'purchase_proforma_lines', type_='foreignkey')
    op.drop_column('purchase_proforma_lines', 'company_id')
    op.alter_column('purchase_proformas', 'credit_amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.drop_constraint('purchase_proformas_ibfk_6', 'purchase_proformas', type_='foreignkey')
    op.drop_column('purchase_proformas', 'company_id')
    op.drop_constraint('reception_lines_ibfk_3', 'reception_lines', type_='foreignkey')
    op.drop_column('reception_lines', 'company_id')
    op.drop_constraint('reception_series_ibfk_3', 'reception_series', type_='foreignkey')
    op.drop_column('reception_series', 'company_id')
    op.drop_constraint('receptions_ibfk_2', 'receptions', type_='foreignkey')
    op.drop_column('receptions', 'company_id')
    op.alter_column('sale_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.drop_constraint('sale_documents_ibfk_2', 'sale_documents', type_='foreignkey')
    op.drop_column('sale_documents', 'company_id')
    op.alter_column('sale_expenses', 'amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('sale_expenses_ibfk_2', 'sale_expenses', type_='foreignkey')
    op.drop_column('sale_expenses', 'company_id')
    op.drop_constraint('sale_invoices_ibfk_3', 'sale_invoices', type_='foreignkey')
    op.drop_column('sale_invoices', 'company_id')
    op.alter_column('sale_payments', 'amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.alter_column('sale_payments', 'rate',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('sale_payments_ibfk_2', 'sale_payments', type_='foreignkey')
    op.drop_column('sale_payments', 'company_id')
    op.alter_column('sale_proforma_lines', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('sale_proforma_lines_ibfk_3', 'sale_proforma_lines', type_='foreignkey')
    op.drop_column('sale_proforma_lines', 'company_id')
    op.alter_column('sale_proformas', 'credit_amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=True)
    op.drop_constraint('sale_proformas_ibfk_6', 'sale_proformas', type_='foreignkey')
    op.drop_column('sale_proformas', 'company_id')
    op.drop_constraint('spec_changes_ibfk_1', 'spec_changes', type_='foreignkey')
    op.drop_column('spec_changes', 'company_id')
    op.drop_constraint('specs_ibfk_1', 'specs', type_='foreignkey')
    op.drop_column('specs', 'company_id')
    op.drop_constraint('vies_requests_ibfk_1', 'vies_requests', type_='foreignkey')
    op.drop_column('vies_requests', 'company_id')
    op.drop_constraint('warehouse_changes_ibfk_1', 'warehouse_changes', type_='foreignkey')
    op.drop_column('warehouse_changes', 'company_id')
    op.drop_constraint('warehouses_ibfk_1', 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'company_id')
    op.alter_column('wh_incoming_rma_lines', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32),
               existing_nullable=False)
    op.drop_constraint('wh_incoming_rma_lines_ibfk_4', 'wh_incoming_rma_lines', type_='foreignkey')
    op.drop_column('wh_incoming_rma_lines', 'company_id')
    op.drop_constraint('wh_incoming_rmas_ibfk_2', 'wh_incoming_rmas', type_='foreignkey')
    op.drop_column('wh_incoming_rmas', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh_incoming_rmas', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('wh_incoming_rmas_ibfk_2', 'wh_incoming_rmas', 'companies', ['company_id'], ['id'])
    op.create_index('ix_wh_incoming_rmas_company_id', 'wh_incoming_rmas', ['company_id'], unique=False)
    op.add_column('wh_incoming_rma_lines', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('wh_incoming_rma_lines_ibfk_4', 'wh_incoming_rma_lines', 'companies', ['company_id'], ['id'])
    op.create_index('ix_wh_incoming_rma_lines_company_id', 'wh_incoming_rma_lines', ['company_id'], unique=False)
    op.alter_column('wh_incoming_rma_lines', 'price',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('warehouses', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('warehouses_ibfk_1', 'warehouses', 'companies', ['company_id'], ['id'])
    op.create_index('ix_warehouses_company_id', 'warehouses', ['company_id'], unique=False)
    op.add_column('warehouse_changes', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('warehouse_changes_ibfk_1', 'warehouse_changes', 'companies', ['company_id'], ['id'])
    op.create_index('ix_warehouse_changes_company_id', 'warehouse_changes', ['company_id'], unique=False)
    op.add_column('vies_requests', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vies_requests_ibfk_1', 'vies_requests', 'companies', ['company_id'], ['id'])
    op.create_index('ix_vies_requests_company_id', 'vies_requests', ['company_id'], unique=False)
    op.add_column('specs', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('specs_ibfk_1', 'specs', 'companies', ['company_id'], ['id'])
    op.create_index('ix_specs_company_id', 'specs', ['company_id'], unique=False)
    op.add_column('spec_changes', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('spec_changes_ibfk_1', 'spec_changes', 'companies', ['company_id'], ['id'])
    op.create_index('ix_spec_changes_company_id', 'spec_changes', ['company_id'], unique=False)
    op.add_column('sale_proformas', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sale_proformas_ibfk_6', 'sale_proformas', 'companies', ['company_id'], ['id'])
    op.create_index('ix_sale_proformas_company_id', 'sale_proformas', ['company_id'], unique=False)
    op.alter_column('sale_proformas', 'credit_amount',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.add_column('sale_proforma_lines', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sale_proforma_lines_ibfk_3', 'sale_proforma_lines', 'companies', ['company_id'], ['id'])
    op.create_index('ix_sale_proforma_lines_company_id', 'sale_proforma_lines', ['company_id'], unique=False)
    op.alter_column('sale_proforma_lines', 'price',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('sale_payments', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sale_payments_ibfk_2', 'sale_payments', 'companies', ['company_id'], ['id'])
    op.create_index('ix_sale_payments_company_id', 'sale_payments', ['company_id'], unique=False)
    op.alter_column('sale_payments', 'rate',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.alter_column('sale_payments', 'amount',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('sale_invoices', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sale_invoices_ibfk_3', 'sale_invoices', 'companies', ['company_id'], ['id'])
    op.create_index('ix_sale_invoices_company_id', 'sale_invoices', ['company_id'], unique=False)
    op.add_column('sale_expenses', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sale_expenses_ibfk_2', 'sale_expenses', 'companies', ['company_id'], ['id'])
    op.create_index('ix_sale_expenses_company_id', 'sale_expenses', ['company_id'], unique=False)
    op.alter_column('sale_expenses', 'amount',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('sale_documents', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sale_documents_ibfk_2', 'sale_documents', 'companies', ['company_id'], ['id'])
    op.create_index('ix_sale_documents_company_id', 'sale_documents', ['company_id'], unique=False)
    op.alter_column('sale_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.add_column('receptions', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('receptions_ibfk_2', 'receptions', 'companies', ['company_id'], ['id'])
    op.create_index('ix_receptions_company_id', 'receptions', ['company_id'], unique=False)
    op.add_column('reception_series', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reception_series_ibfk_3', 'reception_series', 'companies', ['company_id'], ['id'])
    op.create_index('ix_reception_series_company_id', 'reception_series', ['company_id'], unique=False)
    op.add_column('reception_lines', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reception_lines_ibfk_3', 'reception_lines', 'companies', ['company_id'], ['id'])
    op.create_index('ix_reception_lines_company_id', 'reception_lines', ['company_id'], unique=False)
    op.add_column('purchase_proformas', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_proformas_ibfk_6', 'purchase_proformas', 'companies', ['company_id'], ['id'])
    op.create_index('ix_purchase_proformas_company_id', 'purchase_proformas', ['company_id'], unique=False)
    op.alter_column('purchase_proformas', 'credit_amount',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.add_column('purchase_proforma_lines', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_proforma_lines_ibfk_3', 'purchase_proforma_lines', 'companies', ['company_id'], ['id'])
    op.create_index('ix_purchase_proforma_lines_company_id', 'purchase_proforma_lines', ['company_id'], unique=False)
    op.alter_column('purchase_proforma_lines', 'price',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('purchase_payments', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_payments_ibfk_2', 'purchase_payments', 'companies', ['company_id'], ['id'])
    op.create_index('ix_purchase_payments_company_id', 'purchase_payments', ['company_id'], unique=False)
    op.alter_column('purchase_payments', 'rate',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.alter_column('purchase_payments', 'amount',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.add_column('purchase_invoices', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_invoices_ibfk_1', 'purchase_invoices', 'companies', ['company_id'], ['id'])
    op.create_index('ix_purchase_invoices_company_id', 'purchase_invoices', ['company_id'], unique=False)
    op.add_column('purchase_expenses', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_expenses_ibfk_2', 'purchase_expenses', 'companies', ['company_id'], ['id'])
    op.create_index('ix_purchase_expenses_company_id', 'purchase_expenses', ['company_id'], unique=False)
    op.alter_column('purchase_expenses', 'amount',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.add_column('purchase_documents', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_documents_ibfk_2', 'purchase_documents', 'companies', ['company_id'], ['id'])
    op.create_index('ix_purchase_documents_company_id', 'purchase_documents', ['company_id'], unique=False)
    op.alter_column('purchase_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.add_column('partners', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('partners_ibfk_2', 'partners', 'companies', ['company_id'], ['id'])
    op.create_index('ix_partners_company_id', 'partners', ['company_id'], unique=False)
    op.alter_column('partners', 'amount_credit_limit',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.add_column('partner_documents', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('partner_documents_ibfk_2', 'partner_documents', 'companies', ['company_id'], ['id'])
    op.create_index('ix_partner_documents_company_id', 'partner_documents', ['company_id'], unique=False)
    op.alter_column('partner_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.add_column('partner_contacts', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('partner_contacts_ibfk_2', 'partner_contacts', 'companies', ['company_id'], ['id'])
    op.create_index('ix_partner_contacts_company_id', 'partner_contacts', ['company_id'], unique=False)
    op.add_column('partner_accounts', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('partner_accounts_ibfk_2', 'partner_accounts', 'companies', ['company_id'], ['id'])
    op.create_index('ix_partner_accounts_company_id', 'partner_accounts', ['company_id'], unique=False)
    op.add_column('many_manies', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('many_manies_ibfk_3', 'many_manies', 'companies', ['company_id'], ['id'])
    op.create_index('ix_many_manies_company_id', 'many_manies', ['company_id'], unique=False)
    op.add_column('items', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('items_ibfk_1', 'items', 'companies', ['company_id'], ['id'])
    op.create_index('ix_items_company_id', 'items', ['company_id'], unique=False)
    op.add_column('incoming_rmas', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('incoming_rmas_ibfk_1', 'incoming_rmas', 'companies', ['company_id'], ['id'])
    op.create_index('ix_incoming_rmas_company_id', 'incoming_rmas', ['company_id'], unique=False)
    op.add_column('incoming_rma_lines', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('incoming_rma_lines_ibfk_3', 'incoming_rma_lines', 'companies', ['company_id'], ['id'])
    op.create_index('ix_incoming_rma_lines_company_id', 'incoming_rma_lines', ['company_id'], unique=False)
    op.alter_column('incoming_rma_lines', 'price',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('imeis_mask', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('imeis_mask_ibfk_3', 'imeis_mask', 'companies', ['company_id'], ['id'])
    op.create_index('ix_imeis_mask_company_id', 'imeis_mask', ['company_id'], unique=False)
    op.add_column('imeis', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('imeis_ibfk_3', 'imeis', 'companies', ['company_id'], ['id'])
    op.create_index('ix_imeis_company_id', 'imeis', ['company_id'], unique=False)
    op.add_column('expeditions', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('expeditions_ibfk_2', 'expeditions', 'companies', ['company_id'], ['id'])
    op.create_index('ix_expeditions_company_id', 'expeditions', ['company_id'], unique=False)
    op.add_column('expedition_series', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('expedition_series_ibfk_2', 'expedition_series', 'companies', ['company_id'], ['id'])
    op.create_index('ix_expedition_series_company_id', 'expedition_series', ['company_id'], unique=False)
    op.add_column('expedition_lines', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('expedition_lines_ibfk_3', 'expedition_lines', 'companies', ['company_id'], ['id'])
    op.create_index('ix_expedition_lines_company_id', 'expedition_lines', ['company_id'], unique=False)
    op.add_column('credit_note_lines', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('credit_note_lines_ibfk_4', 'credit_note_lines', 'companies', ['company_id'], ['id'])
    op.create_index('ix_credit_note_lines_company_id', 'credit_note_lines', ['company_id'], unique=False)
    op.alter_column('credit_note_lines', 'price',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('couriers', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('couriers_ibfk_1', 'couriers', 'companies', ['company_id'], ['id'])
    op.create_index('ix_couriers_company_id', 'couriers', ['company_id'], unique=False)
    op.add_column('conditions', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('conditions_ibfk_1', 'conditions', 'companies', ['company_id'], ['id'])
    op.create_index('ix_conditions_company_id', 'conditions', ['company_id'], unique=False)
    op.add_column('condition_changes', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('condition_changes_ibfk_1', 'condition_changes', 'companies', ['company_id'], ['id'])
    op.create_index('ix_condition_changes_company_id', 'condition_changes', ['company_id'], unique=False)
    op.add_column('agents', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('agents_ibfk_1', 'agents', 'companies', ['company_id'], ['id'])
    op.create_index('ix_agents_company_id', 'agents', ['company_id'], unique=False)
    op.alter_column('agents', 'fixed_perpiece',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.alter_column('agents', 'from_turnover',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.alter_column('agents', 'from_profit',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.alter_column('agents', 'fixed_salary',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('agent_documents', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('agent_documents_ibfk_2', 'agent_documents', 'companies', ['company_id'], ['id'])
    op.create_index('ix_agent_documents_company_id', 'agent_documents', ['company_id'], unique=False)
    op.alter_column('agent_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.add_column('advanced_lines_definition', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('advanced_lines_definition_ibfk_3', 'advanced_lines_definition', 'companies', ['company_id'], ['id'])
    op.create_index('ix_advanced_lines_definition_company_id', 'advanced_lines_definition', ['company_id'], unique=False)
    op.add_column('advanced_lines', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('advanced_lines_ibfk_3', 'advanced_lines', 'companies', ['company_id'], ['id'])
    op.create_index('ix_advanced_lines_company_id', 'advanced_lines', ['company_id'], unique=False)
    op.alter_column('advanced_lines', 'price',
               existing_type=sa.Float(precision=32),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    # ### end Alembic commands ###
