"""empty message

Revision ID: 733cb92dffd1
Revises: 651f3fff481b
Create Date: 2022-05-04 09:31:16.064773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733cb92dffd1'
down_revision = '651f3fff481b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
