"""empty message

Revision ID: 73f135812b95
Revises: 407501cb5d22
Create Date: 2022-07-29 15:42:55.402632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73f135812b95'
down_revision = '407501cb5d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_proformas', 'external')
    op.drop_column('sale_proformas', 'external')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_proformas', sa.Column('external', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('purchase_proformas', sa.Column('external', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
