"""empty message

Revision ID: 819525d44eb2
Revises: 
Create Date: 2022-05-02 19:12:42.385351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '819525d44eb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_incoming_rmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_rma_id', sa.Integer(), nullable=False),
    sa.Column('inventoried', sa.Boolean(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incoming_rma_id'], ['incoming_rmas.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incoming_rma_id', name='wh_order_from_onlyone_rma_order')
    )
    op.create_table('wh_incoming_rma_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wh_incoming_rma_id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=50), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('problem', sa.String(length=100), nullable=True),
    sa.Column('why', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['wh_incoming_rma_id'], ['wh_incoming_rmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('incoming_rma_lines', sa.Column('sn', sa.String(length=50), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('warranty_end_sup', sa.Date(), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('warranty_end_cust', sa.Date(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('why', sa.String(length=100), nullable=True))
    op.alter_column('incoming_rma_lines', 'problem',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('incoming_rma_lines', 'accepted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('incoming_rma_lines', 'purchase_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('purchase_date', sa.DATE(), nullable=True))
    op.alter_column('incoming_rma_lines', 'accepted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('incoming_rma_lines', 'problem',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('incoming_rma_lines', 'why')
    op.drop_column('incoming_rma_lines', 'warranty_end_cust')
    op.drop_column('incoming_rma_lines', 'warranty_end_sup')
    op.drop_column('incoming_rma_lines', 'sn')
    op.drop_table('wh_incoming_rma_lines')
    op.drop_table('wh_incoming_rmas')
    # ### end Alembic commands ###
