"""change account name size

Revision ID: 82c492748a16
Revises: b86858089c72
Create Date: 2023-03-02 19:16:15.194862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82c492748a16'
down_revision = 'b86858089c72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('accounts', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('description', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###
