"""Added whrmaline.target_condition

Revision ID: 86e4f49a3722
Revises: 056df032ff77
Create Date: 2023-02-15 12:57:23.768401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e4f49a3722'
down_revision = '056df032ff77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh_incoming_rma_lines', sa.Column('target_condition', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wh_incoming_rma_lines', 'target_condition')
    # ### end Alembic commands ###
