"""add_rma_tables

Revision ID: 8e0aea530946
Revises: 
Create Date: 2022-04-19 12:25:41.392773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0aea530946'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_rmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incoming_rma_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_rma_id', sa.Integer(), nullable=True),
    sa.Column('sn', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_description', sa.String(length=100), nullable=False),
    sa.Column('arrival_date', sa.DateTime(), nullable=False),
    sa.Column('defined_as', sa.String(length=100), nullable=False),
    sa.Column('sold_as', sa.String(length=100), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('warehouse_picking_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incoming_rma_id'], ['incoming_rmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incoming_rma_lines')
    op.drop_table('incoming_rmas')
    # ### end Alembic commands ###
