"""empty message

Revision ID: 9d83f57a2812
Revises: 
Create Date: 2022-08-10 18:29:42.545936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d83f57a2812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_invoices', 'external_document')
    op.add_column('purchase_proformas', sa.Column('external', sa.String(length=50), nullable=True))
    op.drop_column('sale_invoices', 'external_document')
    op.add_column('sale_proformas', sa.Column('external', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_proformas', 'external')
    op.add_column('sale_invoices', sa.Column('external_document', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('purchase_proformas', 'external')
    op.add_column('purchase_invoices', sa.Column('external_document', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
