"""empty message

Revision ID: ac575ea7ba3b
Revises: 
Create Date: 2022-04-22 16:13:41.592229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac575ea7ba3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('reception_datetime', sa.DateTime(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('purchased_as', sa.String(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('public_condition', sa.String(length=100), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('expedition_datetime', sa.DateTime(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('sold_to_id', sa.Integer(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('problem', sa.String(length=100), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('accepted', sa.Boolean(), nullable=False))
    op.alter_column('incoming_rma_lines', 'purchase_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('incoming_rma_lines', 'defined_as',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('incoming_rma_lines', 'sold_as',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('incoming_rma_lines', 'sale_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'incoming_rma_lines', 'partners', ['sold_to_id'], ['id'])
    op.drop_column('incoming_rma_lines', 'purchase_description')
    op.drop_column('incoming_rma_lines', 'arrival_date')
    op.drop_column('incoming_rma_lines', 'warehouse_picking_datetime')
    op.drop_column('incoming_rma_lines', 'sn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('sn', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('warehouse_picking_datetime', mysql.DATETIME(), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('arrival_date', mysql.DATETIME(), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('purchase_description', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'incoming_rma_lines', type_='foreignkey')
    op.alter_column('incoming_rma_lines', 'sale_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('incoming_rma_lines', 'sold_as',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('incoming_rma_lines', 'defined_as',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('incoming_rma_lines', 'purchase_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('incoming_rma_lines', 'accepted')
    op.drop_column('incoming_rma_lines', 'problem')
    op.drop_column('incoming_rma_lines', 'sold_to_id')
    op.drop_column('incoming_rma_lines', 'expedition_datetime')
    op.drop_column('incoming_rma_lines', 'public_condition')
    op.drop_column('incoming_rma_lines', 'purchased_as')
    op.drop_column('incoming_rma_lines', 'reception_datetime')
    # ### end Alembic commands ###
