"""add warning column to sale proforma

Revision ID: b0c72a449477
Revises: 06ac09d15102
Create Date: 2022-04-20 10:50:41.796239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c72a449477'
down_revision = '06ac09d15102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_proformas', sa.Column('warning', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_proformas', 'warning')
    # ### end Alembic commands ###
