"""empty message

Revision ID: bcccbd1149d0
Revises: bfd91e44cdb9
Create Date: 2022-05-02 17:24:18.115891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcccbd1149d0'
down_revision = 'bfd91e44cdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wh_incoming_rmas', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh_incoming_rmas', sa.Column('date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
