"""empty message

Revision ID: bfd91e44cdb9
Revises: 4a3af850808e
Create Date: 2022-05-02 17:20:52.692502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd91e44cdb9'
down_revision = '4a3af850808e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh_incoming_rmas', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wh_incoming_rmas', 'date')
    # ### end Alembic commands ###
