"""has_serie_field

Revision ID: cbc51be1a965
Revises: 2b6d3d46bff9
Create Date: 2021-12-15 08:54:59.604055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc51be1a965'
down_revision = '2b6d3d46bff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('has_serie', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'has_serie')
    # ### end Alembic commands ###
