"""empty message

Revision ID: cc49ba91541e
Revises: ed532b67b62f
Create Date: 2022-05-02 12:46:04.897231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc49ba91541e'
down_revision = 'ed532b67b62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_incoming_rmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_rma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incoming_rma_id'], ['incoming_rmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wh_incming_rma_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wh_incoming_rma_id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=50), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('why', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['wh_incoming_rma_id'], ['wh_incoming_rmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('incoming_rmas', 'partner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('incoming_rmas', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming_rmas', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('incoming_rmas', 'partner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('wh_incming_rma_lines')
    op.drop_table('wh_incoming_rmas')
    # ### end Alembic commands ###
