"""partner accounts

Revision ID: d7f5c9a4ee76
Revises: 0c3aa377bfba
Create Date: 2021-12-14 13:16:44.690632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f5c9a4ee76'
down_revision = '0c3aa377bfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('swift', sa.String(length=50), nullable=True),
    sa.Column('bank_address', sa.String(length=50), nullable=True),
    sa.Column('bank_postcode', sa.String(length=50), nullable=True),
    sa.Column('bank_city', sa.String(length=50), nullable=True),
    sa.Column('bank_state', sa.String(length=50), nullable=True),
    sa.Column('bank_country', sa.String(length=50), nullable=True),
    sa.Column('bank_routing', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_accounts')
    # ### end Alembic commands ###
