"""empty message

Revision ID: df8d81a37d92
Revises: 
Create Date: 2022-08-26 09:31:09.796842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8d81a37d92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh_incoming_rmas', sa.Column('dumped', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wh_incoming_rmas', 'dumped')
    # ### end Alembic commands ###
