"""empty message

Revision ID: e5872fa1f37e
Revises: f9069a2c8efd
Create Date: 2022-05-02 15:42:46.114859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5872fa1f37e'
down_revision = 'f9069a2c8efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming_rmas', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming_rmas', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
