"""empty message

Revision ID: e6e12b1df287
Revises: cc49ba91541e
Create Date: 2022-05-02 12:47:18.386731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6e12b1df287'
down_revision = 'cc49ba91541e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_incoming_rma_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wh_incoming_rma_id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=50), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('why', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['wh_incoming_rma_id'], ['wh_incoming_rmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wh_incming_rma_lines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_incming_rma_lines',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wh_incoming_rma_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sn', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('accepted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('why', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['wh_incoming_rma_id'], ['wh_incoming_rmas.id'], name='wh_incming_rma_lines_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('wh_incoming_rma_lines')
    # ### end Alembic commands ###
