"""empty message

Revision ID: ed532b67b62f
Revises: 
Create Date: 2022-05-02 08:52:58.032391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed532b67b62f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('sn', sa.String(length=50), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('warranty_end_sup', sa.Date(), nullable=False))
    op.add_column('incoming_rma_lines', sa.Column('warranty_end_cust', sa.Date(), nullable=True))
    op.add_column('incoming_rma_lines', sa.Column('why', sa.String(length=100), nullable=True))
    op.alter_column('incoming_rma_lines', 'problem',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('incoming_rma_lines', 'accepted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('incoming_rma_lines', 'purchase_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('purchase_date', sa.DATE(), nullable=True))
    op.alter_column('incoming_rma_lines', 'accepted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('incoming_rma_lines', 'problem',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('incoming_rma_lines', 'why')
    op.drop_column('incoming_rma_lines', 'warranty_end_cust')
    op.drop_column('incoming_rma_lines', 'warranty_end_sup')
    op.drop_column('incoming_rma_lines', 'sn')
    # ### end Alembic commands ###
