"""empty message

Revision ID: f07bdbd83e36
Revises: 51464bdf1f6f
Create Date: 2022-04-22 19:00:35.551509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07bdbd83e36'
down_revision = '51464bdf1f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_rma_lines', sa.Column('sn', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incoming_rma_lines', 'sn')
    # ### end Alembic commands ###
