"""empty message

Revision ID: f9069a2c8efd
Revises: fe57daa9da7f
Create Date: 2022-05-02 15:42:10.850056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9069a2c8efd'
down_revision = 'fe57daa9da7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming_rmas', 'partner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming_rmas', 'partner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
