"""float_to_numeric

Revision ID: fb826c52a4a3
Revises: d11b42ff17bb
Create Date: 2022-03-17 10:47:25.201365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb826c52a4a3'
down_revision = 'd11b42ff17bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advanced_lines', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('agent_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('agents', 'fixed_salary',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('agents', 'from_profit',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('agents', 'from_turnover',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('agents', 'fixed_perpiece',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('partner_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('partners', 'amount_credit_limit',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('purchase_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('purchase_expenses', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('purchase_payments', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('purchase_payments', 'rate',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('purchase_proforma_lines', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('purchase_proformas', 'credit_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('sale_documents', 'document',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('sale_expenses', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('sale_payments', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('sale_payments', 'rate',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('sale_proforma_lines', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('sale_proformas', 'credit_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_proformas', 'credit_amount',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sale_proforma_lines', 'price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('sale_payments', 'rate',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('sale_payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('sale_expenses', 'amount',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('sale_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('purchase_proformas', 'credit_amount',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('purchase_proforma_lines', 'price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('purchase_payments', 'rate',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('purchase_payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('purchase_expenses', 'amount',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('purchase_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('partners', 'amount_credit_limit',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('partner_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('agents', 'fixed_perpiece',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('agents', 'from_turnover',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('agents', 'from_profit',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('agents', 'fixed_salary',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('agent_documents', 'document',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('advanced_lines', 'price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
