"""empty message

Revision ID: fe57daa9da7f
Revises: e6e12b1df287
Create Date: 2022-05-02 13:48:42.115564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe57daa9da7f'
down_revision = 'e6e12b1df287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh_incoming_rma_lines', sa.Column('problem', sa.String(length=100), nullable=True))
    op.create_unique_constraint('wh_order_from_onlyone_rma_order', 'wh_incoming_rmas', ['incoming_rma_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wh_order_from_onlyone_rma_order', 'wh_incoming_rmas', type_='unique')
    op.drop_column('wh_incoming_rma_lines', 'problem')
    # ### end Alembic commands ###
