# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\apply_credit_note_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1017, 408)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 471, 211))
        self.groupBox.setObjectName("groupBox")
        self.available = QtWidgets.QTableView(self.groupBox)
        self.available.setGeometry(QtCore.QRect(0, 20, 471, 191))
        self.available.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.available.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.available.setObjectName("available")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(630, 50, 311, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.applied = QtWidgets.QTableView(self.groupBox_2)
        self.applied.setGeometry(QtCore.QRect(0, 20, 311, 191))
        self.applied.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.applied.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.applied.setObjectName("applied")
        self.exit = QtWidgets.QToolButton(Dialog)
        self.exit.setGeometry(QtCore.QRect(870, 320, 71, 61))
        self.exit.setStyleSheet("background:lightgray; ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon)
        self.exit.setIconSize(QtCore.QSize(24, 24))
        self.exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exit.setAutoRaise(True)
        self.exit.setObjectName("exit")
        self.delete_ = QtWidgets.QPushButton(Dialog)
        self.delete_.setGeometry(QtCore.QRect(865, 267, 75, 23))
        self.delete_.setObjectName("delete_")
        self.add = QtWidgets.QToolButton(Dialog)
        self.add.setGeometry(QtCore.QRect(520, 130, 91, 61))
        self.add.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/right_arrow"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon1)
        self.add.setIconSize(QtCore.QSize(32, 32))
        self.add.setCheckable(False)
        self.add.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.add.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.add.setAutoRaise(True)
        self.add.setObjectName("add")

        self.retranslateUi(Dialog)
        self.exit.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Apply Credit Note to Invoices"))
        self.groupBox.setTitle(_translate("Dialog", "Available:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Applied:"))
        self.exit.setText(_translate("Dialog", "EXIT"))
        self.delete_.setText(_translate("Dialog", "Delete"))
        self.add.setText(_translate("Dialog", "Add"))
import icons_rc
