# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\available_stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1027, 831)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warehouse"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.view = ClipView(Form)
        self.view.setGeometry(QtCore.QRect(50, 120, 941, 611))
        self.view.setObjectName("view")
        self.exit = QtWidgets.QToolButton(Form)
        self.exit.setGeometry(QtCore.QRect(920, 750, 70, 60))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon1)
        self.exit.setIconSize(QtCore.QSize(32, 32))
        self.exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exit.setAutoRaise(True)
        self.exit.setObjectName("exit")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 20, 941, 81))
        self.groupBox.setObjectName("groupBox")
        self.description = QtWidgets.QLineEdit(self.groupBox)
        self.description.setGeometry(QtCore.QRect(30, 20, 330, 20))
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.condition = QtWidgets.QLineEdit(self.groupBox)
        self.condition.setGeometry(QtCore.QRect(370, 20, 130, 20))
        self.condition.setAlignment(QtCore.Qt.AlignCenter)
        self.condition.setObjectName("condition")
        self.spec = QtWidgets.QLineEdit(self.groupBox)
        self.spec.setGeometry(QtCore.QRect(510, 20, 130, 20))
        self.spec.setText("")
        self.spec.setAlignment(QtCore.Qt.AlignCenter)
        self.spec.setObjectName("spec")
        self.warehouse = QtWidgets.QLineEdit(self.groupBox)
        self.warehouse.setGeometry(QtCore.QRect(650, 20, 130, 20))
        self.warehouse.setAlignment(QtCore.Qt.AlignCenter)
        self.warehouse.setObjectName("warehouse")
        self.apply = QtWidgets.QPushButton(self.groupBox)
        self.apply.setGeometry(QtCore.QRect(811, 16, 110, 45))
        self.apply.setDefault(True)
        self.apply.setObjectName("apply")
        self.incoming = QtWidgets.QRadioButton(self.groupBox)
        self.incoming.setGeometry(QtCore.QRect(710, 50, 70, 17))
        self.incoming.setObjectName("incoming")
        self.physical = QtWidgets.QRadioButton(self.groupBox)
        self.physical.setGeometry(QtCore.QRect(630, 50, 70, 17))
        self.physical.setCheckable(True)
        self.physical.setChecked(True)
        self.physical.setAutoExclusive(True)
        self.physical.setObjectName("physical")
        self.excel = QtWidgets.QToolButton(Form)
        self.excel.setGeometry(QtCore.QRect(830, 750, 70, 60))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/excel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.excel.setIcon(icon2)
        self.excel.setIconSize(QtCore.QSize(32, 32))
        self.excel.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.excel.setAutoRaise(True)
        self.excel.setObjectName("excel")
        self.whatsapp = QtWidgets.QToolButton(Form)
        self.whatsapp.setGeometry(QtCore.QRect(740, 750, 70, 60))
        self.whatsapp.setMinimumSize(QtCore.QSize(70, 60))
        self.whatsapp.setMaximumSize(QtCore.QSize(70, 60))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\uis\\../app/icons/whatsapp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.whatsapp.setIcon(icon3)
        self.whatsapp.setIconSize(QtCore.QSize(40, 40))
        self.whatsapp.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.whatsapp.setAutoRaise(True)
        self.whatsapp.setObjectName("whatsapp")

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Available Stock"))
        self.exit.setText(_translate("Form", "Exit"))
        self.groupBox.setTitle(_translate("Form", "FILTERS:"))
        self.description.setPlaceholderText(_translate("Form", "Description..."))
        self.condition.setPlaceholderText(_translate("Form", "Condition..."))
        self.spec.setPlaceholderText(_translate("Form", "Spec..."))
        self.warehouse.setPlaceholderText(_translate("Form", "Warehouse..."))
        self.apply.setText(_translate("Form", "Apply"))
        self.incoming.setText(_translate("Form", "Incoming"))
        self.physical.setText(_translate("Form", "Physical"))
        self.excel.setText(_translate("Form", "Excel"))
        self.whatsapp.setText(_translate("Form", "WhatsApp"))
from clipview import ClipView
import icons_rc
