# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\apply_credit_note_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 408)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 211, 211))
        self.groupBox.setObjectName("groupBox")
        self.available_view = QtWidgets.QListView(self.groupBox)
        self.available_view.setGeometry(QtCore.QRect(0, 20, 211, 191))
        self.available_view.setObjectName("available_view")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 50, 211, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.available_view_2 = QtWidgets.QListView(self.groupBox_2)
        self.available_view_2.setGeometry(QtCore.QRect(0, 20, 211, 191))
        self.available_view_2.setObjectName("available_view_2")
        self.save_button_2 = QtWidgets.QToolButton(Dialog)
        self.save_button_2.setGeometry(QtCore.QRect(510, 320, 71, 61))
        self.save_button_2.setStyleSheet("background:lightgray; ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button_2.setIcon(icon)
        self.save_button_2.setIconSize(QtCore.QSize(24, 24))
        self.save_button_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.save_button_2.setAutoRaise(True)
        self.save_button_2.setObjectName("save_button_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(505, 268, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.add = QtWidgets.QToolButton(Dialog)
        self.add.setGeometry(QtCore.QRect(260, 130, 91, 61))
        self.add.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/right_arrow"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon1)
        self.add.setIconSize(QtCore.QSize(32, 32))
        self.add.setCheckable(False)
        self.add.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.add.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.add.setAutoRaise(True)
        self.add.setObjectName("add")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Apply Credit Note to Invoices"))
        self.groupBox.setTitle(_translate("Dialog", "Available:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Applied:"))
        self.save_button_2.setText(_translate("Dialog", "EXIT"))
        self.pushButton.setText(_translate("Dialog", "Delete"))
        self.add.setText(_translate("Dialog", "Add"))
import icons_rc
