# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\condition.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConditionForm(object):
    def setupUi(self, ConditionForm):
        ConditionForm.setObjectName("ConditionForm")
        ConditionForm.resize(461, 322)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warehouse"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConditionForm.setWindowIcon(icon)
        self.view = QtWidgets.QListView(ConditionForm)
        self.view.setGeometry(QtCore.QRect(50, 60, 261, 211))
        self.view.setObjectName("view")
        self.add = QtWidgets.QPushButton(ConditionForm)
        self.add.setGeometry(QtCore.QRect(330, 30, 93, 21))
        self.add.setObjectName("add")
        self.delete_2 = QtWidgets.QPushButton(ConditionForm)
        self.delete_2.setGeometry(QtCore.QRect(330, 200, 93, 28))
        self.delete_2.setObjectName("delete_2")
        self.exit = QtWidgets.QPushButton(ConditionForm)
        self.exit.setGeometry(QtCore.QRect(330, 240, 93, 28))
        self.exit.setObjectName("exit")
        self.input = QtWidgets.QLineEdit(ConditionForm)
        self.input.setGeometry(QtCore.QRect(50, 30, 261, 22))
        self.input.setObjectName("input")

        self.retranslateUi(ConditionForm)
        self.exit.clicked.connect(ConditionForm.close)
        QtCore.QMetaObject.connectSlotsByName(ConditionForm)

    def retranslateUi(self, ConditionForm):
        _translate = QtCore.QCoreApplication.translate
        ConditionForm.setWindowTitle(_translate("ConditionForm", "Conditions"))
        self.add.setText(_translate("ConditionForm", "Add"))
        self.delete_2.setText(_translate("ConditionForm", "Delete"))
        self.exit.setText(_translate("ConditionForm", "Exit"))
import icons_rc
