# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\courier.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CourierForm(object):
    def setupUi(self, CourierForm):
        CourierForm.setObjectName("CourierForm")
        CourierForm.resize(461, 322)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warehouse"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CourierForm.setWindowIcon(icon)
        self.view = QtWidgets.QListView(CourierForm)
        self.view.setGeometry(QtCore.QRect(50, 60, 261, 211))
        self.view.setObjectName("view")
        self.add = QtWidgets.QPushButton(CourierForm)
        self.add.setGeometry(QtCore.QRect(330, 30, 93, 21))
        self.add.setObjectName("add")
        self.delete_2 = QtWidgets.QPushButton(CourierForm)
        self.delete_2.setGeometry(QtCore.QRect(330, 200, 93, 28))
        self.delete_2.setObjectName("delete_2")
        self.exit = QtWidgets.QPushButton(CourierForm)
        self.exit.setGeometry(QtCore.QRect(330, 240, 93, 28))
        self.exit.setObjectName("exit")
        self.input = QtWidgets.QLineEdit(CourierForm)
        self.input.setGeometry(QtCore.QRect(50, 30, 261, 22))
        self.input.setObjectName("input")

        self.retranslateUi(CourierForm)
        self.exit.clicked.connect(CourierForm.close)
        QtCore.QMetaObject.connectSlotsByName(CourierForm)

    def retranslateUi(self, CourierForm):
        _translate = QtCore.QCoreApplication.translate
        CourierForm.setWindowTitle(_translate("CourierForm", "Specs"))
        self.add.setText(_translate("CourierForm", "Add"))
        self.delete_2.setText(_translate("CourierForm", "Delete"))
        self.exit.setText(_translate("CourierForm", "Exit"))
import icons_rc
