# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\condition_change_form.py'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConditionChange(object):
    def setupUi(self, ConditionChange):
        ConditionChange.setObjectName("ConditionChange")
        ConditionChange.resize(526, 382)
        self.new_condition = QtWidgets.QLineEdit(ConditionChange)
        self.new_condition.setGeometry(QtCore.QRect(180, 220, 161, 22))
        self.new_condition.setReadOnly(False)
        self.new_condition.setObjectName("new_condition")
        self.update = QtWidgets.QPushButton(ConditionChange)
        self.update.setGeometry(QtCore.QRect(370, 220, 101, 28))
        self.update.setObjectName("update")
        self.layoutWidget = QtWidgets.QWidget(ConditionChange)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 40, 321, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sn = QtWidgets.QLineEdit(self.layoutWidget)
        self.sn.setMinimumSize(QtCore.QSize(261, 22))
        self.sn.setMaximumSize(QtCore.QSize(261, 22))
        self.sn.setAlignment(QtCore.Qt.AlignCenter)
        self.sn.setObjectName("sn")
        self.horizontalLayout.addWidget(self.sn)
        self.label_3 = QtWidgets.QLabel(ConditionChange)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 111, 20))
        self.label_3.setObjectName("label_3")
        self.exit = QtWidgets.QPushButton(ConditionChange)
        self.exit.setGeometry(QtCore.QRect(370, 300, 101, 28))
        self.exit.setObjectName("exit")
        self.current_condition = QtWidgets.QLineEdit(ConditionChange)
        self.current_condition.setGeometry(QtCore.QRect(180, 160, 161, 22))
        self.current_condition.setReadOnly(True)
        self.current_condition.setObjectName("current_condition")
        self.layoutWidget_2 = QtWidgets.QWidget(ConditionChange)
        self.layoutWidget_2.setGeometry(QtCore.QRect(90, 90, 338, 24))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.description = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.description.setMinimumSize(QtCore.QSize(261, 22))
        self.description.setMaximumSize(QtCore.QSize(261, 22))
        self.description.setReadOnly(True)
        self.description.setObjectName("description")
        self.horizontalLayout_2.addWidget(self.description)
        self.label_4 = QtWidgets.QLabel(ConditionChange)
        self.label_4.setGeometry(QtCore.QRect(70, 220, 101, 20))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(ConditionChange)
        QtCore.QMetaObject.connectSlotsByName(ConditionChange)

    def retranslateUi(self, ConditionChange):
        _translate = QtCore.QCoreApplication.translate
        ConditionChange.setWindowTitle(_translate("ConditionChange", "Dialog"))
        self.update.setText(_translate("ConditionChange", "Update"))
        self.label.setText(_translate("ConditionChange", "IMEI/SN:"))
        self.sn.setPlaceholderText(_translate("ConditionChange", "Press enter to search .. "))
        self.label_3.setText(_translate("ConditionChange", "Current Condition:"))
        self.exit.setText(_translate("ConditionChange", "Exit"))
        self.label_2.setText(_translate("ConditionChange", "Description:"))
        self.label_4.setText(_translate("ConditionChange", "New Condition:"))
