# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\change_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeForm(object):
    def setupUi(self, ChangeForm):
        ChangeForm.setObjectName("ChangeForm")
        ChangeForm.resize(851, 758)
        self.view = QtWidgets.QTableView(ChangeForm)
        self.view.setGeometry(QtCore.QRect(60, 110, 561, 611))
        self.view.setObjectName("view")
        self.sn = QtWidgets.QLineEdit(ChangeForm)
        self.sn.setGeometry(QtCore.QRect(160, 71, 331, 20))
        self.sn.setAlignment(QtCore.Qt.AlignCenter)
        self.sn.setObjectName("sn")
        self.apply = QtWidgets.QPushButton(ChangeForm)
        self.apply.setGeometry(QtCore.QRect(680, 230, 111, 41))
        self.apply.setStyleSheet("font:bold; ")
        self.apply.setAutoDefault(False)
        self.apply.setDefault(False)
        self.apply.setObjectName("apply")
        self.exit = QtWidgets.QToolButton(ChangeForm)
        self.exit.setGeometry(QtCore.QRect(730, 650, 91, 71))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon)
        self.exit.setIconSize(QtCore.QSize(40, 40))
        self.exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exit.setAutoRaise(True)
        self.exit.setObjectName("exit")
        self.widget = QtWidgets.QWidget(ChangeForm)
        self.widget.setGeometry(QtCore.QRect(650, 110, 167, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font:bold;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.new_ = QtWidgets.QLineEdit(self.widget)
        self.new_.setReadOnly(False)
        self.new_.setObjectName("new_")
        self.horizontalLayout.addWidget(self.new_)

        self.retranslateUi(ChangeForm)
        self.exit.clicked.connect(ChangeForm.accept)
        QtCore.QMetaObject.connectSlotsByName(ChangeForm)

    def retranslateUi(self, ChangeForm):
        _translate = QtCore.QCoreApplication.translate
        ChangeForm.setWindowTitle(_translate("ChangeForm", "Dialog"))
        self.sn.setPlaceholderText(_translate("ChangeForm", " IMEI/SN ..."))
        self.apply.setText(_translate("ChangeForm", "Apply"))
        self.exit.setText(_translate("ChangeForm", "Exit"))
        self.label.setText(_translate("ChangeForm", "New:"))
import icons_rc
