# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\change_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeForm(object):
    def setupUi(self, ChangeForm):
        ChangeForm.setObjectName("ChangeForm")
        ChangeForm.resize(891, 478)
        self.view = ClipView(ChangeForm)
        self.view.setGeometry(QtCore.QRect(60, 60, 461, 391))
        self.view.setObjectName("view")
        self.sn = QtWidgets.QLineEdit(ChangeForm)
        self.sn.setGeometry(QtCore.QRect(60, 30, 331, 20))
        self.sn.setAlignment(QtCore.Qt.AlignCenter)
        self.sn.setObjectName("sn")
        self.apply = QtWidgets.QPushButton(ChangeForm)
        self.apply.setGeometry(QtCore.QRect(585, 159, 251, 61))
        self.apply.setStyleSheet("font:bold; ")
        self.apply.setAutoDefault(False)
        self.apply.setDefault(False)
        self.apply.setObjectName("apply")
        self.comment = QtWidgets.QLineEdit(ChangeForm)
        self.comment.setGeometry(QtCore.QRect(602, 110, 271, 20))
        self.comment.setObjectName("comment")
        self.label_2 = QtWidgets.QLabel(ChangeForm)
        self.label_2.setGeometry(QtCore.QRect(540, 110, 61, 16))
        self.label_2.setObjectName("label_2")
        self.exit = QtWidgets.QPushButton(ChangeForm)
        self.exit.setGeometry(QtCore.QRect(760, 430, 91, 31))
        self.exit.setAutoDefault(False)
        self.exit.setObjectName("exit")
        self.new_ = QtWidgets.QLineEdit(ChangeForm)
        self.new_.setGeometry(QtCore.QRect(602, 70, 133, 20))
        self.new_.setReadOnly(False)
        self.new_.setObjectName("new_")
        self.label = QtWidgets.QLabel(ChangeForm)
        self.label.setGeometry(QtCore.QRect(570, 70, 26, 16))
        self.label.setStyleSheet("font:bold;")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(ChangeForm)
        self.label_3.setGeometry(QtCore.QRect(600, 270, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-weight:bold; ")
        self.label_3.setObjectName("label_3")
        self.counter = QtWidgets.QLabel(ChangeForm)
        self.counter.setGeometry(QtCore.QRect(780, 270, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.counter.setFont(font)
        self.counter.setStyleSheet("font-weight:bold ;")
        self.counter.setText("")
        self.counter.setObjectName("counter")

        self.retranslateUi(ChangeForm)
        self.exit.clicked.connect(ChangeForm.close)
        QtCore.QMetaObject.connectSlotsByName(ChangeForm)

    def retranslateUi(self, ChangeForm):
        _translate = QtCore.QCoreApplication.translate
        ChangeForm.setWindowTitle(_translate("ChangeForm", "Dialog"))
        self.sn.setPlaceholderText(_translate("ChangeForm", " IMEI/SN ..."))
        self.apply.setText(_translate("ChangeForm", "Apply"))
        self.label_2.setText(_translate("ChangeForm", "Comment:"))
        self.exit.setText(_translate("ChangeForm", "Exit"))
        self.label.setText(_translate("ChangeForm", "New:"))
        self.label_3.setText(_translate("ChangeForm", "Counter:"))
from clipview import ClipView
import icons_rc
