# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\document_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DocumentsForm(object):
    def setupUi(self, DocumentsForm):
        DocumentsForm.setObjectName("DocumentsForm")
        DocumentsForm.resize(668, 364)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/document"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DocumentsForm.setWindowIcon(icon)
        DocumentsForm.setStyleSheet("background:white;")
        self.add_button = QtWidgets.QToolButton(DocumentsForm)
        self.add_button.setGeometry(QtCore.QRect(360, 270, 91, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/add_document"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon1)
        self.add_button.setIconSize(QtCore.QSize(40, 40))
        self.add_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.add_button.setAutoRaise(True)
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QToolButton(DocumentsForm)
        self.delete_button.setGeometry(QtCore.QRect(460, 270, 91, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/delete"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon2)
        self.delete_button.setIconSize(QtCore.QSize(40, 40))
        self.delete_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.delete_button.setAutoRaise(True)
        self.delete_button.setObjectName("delete_button")
        self.export_button = QtWidgets.QToolButton(DocumentsForm)
        self.export_button.setGeometry(QtCore.QRect(260, 270, 91, 61))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/export"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_button.setIcon(icon3)
        self.export_button.setIconSize(QtCore.QSize(40, 40))
        self.export_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.export_button.setAutoRaise(True)
        self.export_button.setObjectName("export_button")
        self.document_view = QtWidgets.QListView(DocumentsForm)
        self.document_view.setGeometry(QtCore.QRect(10, 30, 641, 201))
        self.document_view.setObjectName("document_view")
        self.exit_button = QtWidgets.QToolButton(DocumentsForm)
        self.exit_button.setGeometry(QtCore.QRect(560, 270, 91, 61))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon4)
        self.exit_button.setIconSize(QtCore.QSize(40, 40))
        self.exit_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exit_button.setAutoRaise(True)
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(DocumentsForm)
        self.exit_button.clicked.connect(DocumentsForm.close)
        QtCore.QMetaObject.connectSlotsByName(DocumentsForm)

    def retranslateUi(self, DocumentsForm):
        _translate = QtCore.QCoreApplication.translate
        DocumentsForm.setWindowTitle(_translate("DocumentsForm", "Documents"))
        self.add_button.setText(_translate("DocumentsForm", "Add"))
        self.delete_button.setText(_translate("DocumentsForm", "Delete"))
        self.export_button.setText(_translate("DocumentsForm", "Export"))
        self.exit_button.setText(_translate("DocumentsForm", "Exit"))
import icons_rc
