# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\discount_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1489, 707)
        self.view = QtWidgets.QTableView(Form)
        self.view.setGeometry(QtCore.QRect(40, 70, 1431, 531))
        self.view.setAlternatingRowColors(True)
        self.view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.view.setSortingEnabled(True)
        self.view.setObjectName("view")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(40, 610, 131, 28))
        self.add.setObjectName("add")
        self.remove = QtWidgets.QPushButton(Form)
        self.remove.setGeometry(QtCore.QRect(180, 610, 131, 28))
        self.remove.setObjectName("remove")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(1380, 650, 93, 28))
        self.exit.setObjectName("exit")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(1270, 650, 93, 28))
        self.save.setObjectName("save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dialog"))
        self.label.setText(_translate("Form", "Discounts"))
        self.add.setText(_translate("Form", "Add (Ctrl+n)"))
        self.remove.setText(_translate("Form", "Delete (Ctrl+d)"))
        self.exit.setText(_translate("Form", "Exit"))
        self.save.setText(_translate("Form", "Save"))
