# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\free_line_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(521, 220)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 170, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(71, 42, 388, 122))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.description = QtWidgets.QLineEdit(self.layoutWidget)
        self.description.setMinimumSize(QtCore.QSize(311, 20))
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.tax = QtWidgets.QComboBox(self.layoutWidget)
        self.tax.setMaximumSize(QtCore.QSize(38, 20))
        self.tax.setObjectName("tax")
        self.tax.addItem("")
        self.tax.addItem("")
        self.tax.addItem("")
        self.tax.addItem("")
        self.gridLayout.addWidget(self.tax, 3, 1, 1, 1)
        self.price = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.price.setMaximumSize(QtCore.QSize(81, 20))
        self.price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.price.setMinimum(-99999999.0)
        self.price.setMaximum(99999999.0)
        self.price.setProperty("value", 0.0)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 2, 1, 1, 1)
        self.quantity = QtWidgets.QSpinBox(self.layoutWidget)
        self.quantity.setMaximumSize(QtCore.QSize(55, 20))
        self.quantity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.quantity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.quantity.setMinimum(1)
        self.quantity.setMaximum(99999)
        self.quantity.setProperty("value", 1)
        self.quantity.setObjectName("quantity")
        self.gridLayout.addWidget(self.quantity, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.accept) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.description, self.quantity)
        Dialog.setTabOrder(self.quantity, self.price)
        Dialog.setTabOrder(self.price, self.tax)
        Dialog.setTabOrder(self.tax, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Insert free line"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Description:"))
        self.label_2.setText(_translate("Dialog", "Quantity:"))
        self.label_3.setText(_translate("Dialog", "Unit/Price:"))
        self.label_4.setText(_translate("Dialog", "Tax:"))
        self.tax.setCurrentText(_translate("Dialog", "0"))
        self.tax.setItemText(0, _translate("Dialog", "0"))
        self.tax.setItemText(1, _translate("Dialog", "21"))
        self.tax.setItemText(2, _translate("Dialog", "10"))
        self.tax.setItemText(3, _translate("Dialog", "4"))
