# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\free_line_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(521, 321)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(320, 270, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 270, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 70, 81, 16))
        self.label.setObjectName("label")
        self.description = QtWidgets.QLineEdit(Dialog)
        self.description.setGeometry(QtCore.QRect(160, 70, 291, 20))
        self.description.setObjectName("description")
        self.quantity = QtWidgets.QSpinBox(Dialog)
        self.quantity.setGeometry(QtCore.QRect(160, 110, 101, 22))
        self.quantity.setMaximum(99999)
        self.quantity.setProperty("value", 1)
        self.quantity.setObjectName("quantity")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 61, 20))
        self.label_3.setObjectName("label_3")
        self.price = QtWidgets.QDoubleSpinBox(Dialog)
        self.price.setGeometry(QtCore.QRect(160, 160, 101, 22))
        self.price.setMaximum(99999999.0)
        self.price.setProperty("value", 1.0)
        self.price.setObjectName("price")
        self.tax = QtWidgets.QComboBox(Dialog)
        self.tax.setGeometry(QtCore.QRect(160, 210, 101, 22))
        self.tax.setObjectName("tax")
        self.tax.addItem("")
        self.tax.addItem("")
        self.tax.addItem("")
        self.tax.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 210, 31, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.accept)
        self.pushButton_2.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Insert free line"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Description:"))
        self.label_2.setText(_translate("Dialog", "quantity:"))
        self.label_3.setText(_translate("Dialog", "Unit/Price:"))
        self.tax.setCurrentText(_translate("Dialog", "21"))
        self.tax.setItemText(0, _translate("Dialog", "0"))
        self.tax.setItemText(1, _translate("Dialog", "21"))
        self.tax.setItemText(2, _translate("Dialog", "10"))
        self.tax.setItemText(3, _translate("Dialog", "4"))
        self.label_4.setText(_translate("Dialog", "Tax:"))
