# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\inventory_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryForm(object):
    def setupUi(self, InventoryForm):
        InventoryForm.setObjectName("InventoryForm")
        InventoryForm.resize(868, 731)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warehouse"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InventoryForm.setWindowIcon(icon)
        InventoryForm.setStyleSheet("background:white; ")
        self.view = QtWidgets.QTableView(InventoryForm)
        self.view.setGeometry(QtCore.QRect(80, 40, 731, 611))
        self.view.setObjectName("view")

        self.retranslateUi(InventoryForm)
        QtCore.QMetaObject.connectSlotsByName(InventoryForm)

    def retranslateUi(self, InventoryForm):
        _translate = QtCore.QCoreApplication.translate
        InventoryForm.setWindowTitle(_translate("InventoryForm", "Inventory"))
import icons_rc
