# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\invoice_payment_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 534)
        self.full = QtWidgets.QGroupBox(Form)
        self.full.setGeometry(QtCore.QRect(50, 60, 921, 61))
        self.full.setCheckable(True)
        self.full.setObjectName("full")
        self.date = QtWidgets.QLineEdit(self.full)
        self.date.setGeometry(QtCore.QRect(81, 20, 81, 22))
        self.date.setMinimumSize(QtCore.QSize(81, 22))
        self.date.setMaximumSize(QtCore.QSize(81, 22))
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.amount = QtWidgets.QLineEdit(self.full)
        self.amount.setGeometry(QtCore.QRect(223, 20, 168, 22))
        self.amount.setAlignment(QtCore.Qt.AlignCenter)
        self.amount.setReadOnly(True)
        self.amount.setObjectName("amount")
        self.label_6 = QtWidgets.QLabel(self.full)
        self.label_6.setGeometry(QtCore.QRect(168, 16, 49, 30))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.full)
        self.label_8.setGeometry(QtCore.QRect(397, 16, 31, 30))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.full)
        self.label.setGeometry(QtCore.QRect(44, 16, 31, 30))
        self.label.setObjectName("label")
        self.rate = QtWidgets.QLineEdit(self.full)
        self.rate.setGeometry(QtCore.QRect(434, 20, 167, 22))
        self.rate.setObjectName("rate")
        self.label_7 = QtWidgets.QLabel(self.full)
        self.label_7.setGeometry(QtCore.QRect(607, 16, 27, 30))
        self.label_7.setObjectName("label_7")
        self.add = QtWidgets.QToolButton(self.full)
        self.add.setGeometry(QtCore.QRect(846, 16, 65, 30))
        self.add.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        self.add.setIconSize(QtCore.QSize(24, 24))
        self.add.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.add.setAutoRaise(True)
        self.add.setObjectName("add")
        self.info = QtWidgets.QLineEdit(self.full)
        self.info.setGeometry(QtCore.QRect(640, 20, 200, 22))
        self.info.setMinimumSize(QtCore.QSize(200, 22))
        self.info.setMaximumSize(QtCore.QSize(200, 22))
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.partial = QtWidgets.QGroupBox(Form)
        self.partial.setGeometry(QtCore.QRect(50, 149, 921, 291))
        self.partial.setCheckable(True)
        self.partial.setObjectName("partial")
        self.view = QtWidgets.QTableView(self.partial)
        self.view.setGeometry(QtCore.QRect(46, 40, 831, 241))
        self.view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.view.setObjectName("view")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(880, 470, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.accept)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Invoice Payment"))
        self.full.setTitle(_translate("Form", "Full Payment"))
        self.date.setPlaceholderText(_translate("Form", "ddmmyyyy"))
        self.label_6.setText(_translate("Form", "Amount:"))
        self.label_8.setText(_translate("Form", "Rate:"))
        self.label.setText(_translate("Form", "Date:"))
        self.rate.setText(_translate("Form", "1"))
        self.label_7.setText(_translate("Form", "Info:"))
        self.add.setText(_translate("Form", "Add"))
        self.partial.setTitle(_translate("Form", "Partial Payment:"))
        self.pushButton.setText(_translate("Form", "Exit"))
import icons_rc
