# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\inventory_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryForm(object):
    def setupUi(self, InventoryForm):
        InventoryForm.setObjectName("InventoryForm")
        InventoryForm.resize(1027, 1016)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warehouse"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InventoryForm.setWindowIcon(icon)
        InventoryForm.setStyleSheet("")
        self.view = ClipView(InventoryForm)
        self.view.setGeometry(QtCore.QRect(50, 170, 941, 711))
        self.view.setObjectName("view")
        self.toolButton = QtWidgets.QToolButton(InventoryForm)
        self.toolButton.setGeometry(QtCore.QRect(910, 900, 81, 81))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(32, 32))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.groupBox = QtWidgets.QGroupBox(InventoryForm)
        self.groupBox.setGeometry(QtCore.QRect(50, 20, 941, 131))
        self.groupBox.setObjectName("groupBox")
        self.description = ClipLineEdit(self.groupBox)
        self.description.setGeometry(QtCore.QRect(30, 50, 321, 20))
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.condition = QtWidgets.QLineEdit(self.groupBox)
        self.condition.setGeometry(QtCore.QRect(360, 50, 113, 20))
        self.condition.setAlignment(QtCore.Qt.AlignCenter)
        self.condition.setObjectName("condition")
        self.spec = QtWidgets.QLineEdit(self.groupBox)
        self.spec.setGeometry(QtCore.QRect(490, 50, 113, 20))
        self.spec.setText("")
        self.spec.setAlignment(QtCore.Qt.AlignCenter)
        self.spec.setObjectName("spec")
        self.warehouse = QtWidgets.QLineEdit(self.groupBox)
        self.warehouse.setGeometry(QtCore.QRect(630, 50, 161, 20))
        self.warehouse.setAlignment(QtCore.Qt.AlignCenter)
        self.warehouse.setObjectName("warehouse")
        self.apply = QtWidgets.QPushButton(self.groupBox)
        self.apply.setGeometry(QtCore.QRect(830, 40, 91, 31))
        self.apply.setDefault(True)
        self.apply.setObjectName("apply")
        self.date = QtWidgets.QLineEdit(self.groupBox)
        self.date.setGeometry(QtCore.QRect(270, 90, 201, 22))
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(114, 90, 111, 20))
        self.label.setObjectName("label")
        self.excel = QtWidgets.QToolButton(InventoryForm)
        self.excel.setGeometry(QtCore.QRect(810, 900, 81, 81))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/excel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.excel.setIcon(icon2)
        self.excel.setIconSize(QtCore.QSize(32, 32))
        self.excel.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.excel.setObjectName("excel")

        self.retranslateUi(InventoryForm)
        self.toolButton.clicked.connect(InventoryForm.close)
        QtCore.QMetaObject.connectSlotsByName(InventoryForm)

    def retranslateUi(self, InventoryForm):
        _translate = QtCore.QCoreApplication.translate
        InventoryForm.setWindowTitle(_translate("InventoryForm", "Inventory"))
        self.toolButton.setText(_translate("InventoryForm", "Exit"))
        self.groupBox.setTitle(_translate("InventoryForm", "FILTERS:"))
        self.description.setPlaceholderText(_translate("InventoryForm", "Description or SN/Imei ..."))
        self.condition.setPlaceholderText(_translate("InventoryForm", "Condition..."))
        self.spec.setPlaceholderText(_translate("InventoryForm", "Spec..."))
        self.warehouse.setPlaceholderText(_translate("InventoryForm", "Warehouse..."))
        self.apply.setText(_translate("InventoryForm", "Apply"))
        self.date.setPlaceholderText(_translate("InventoryForm", "ddmmyyyy"))
        self.label.setText(_translate("InventoryForm", "Historical Iventory:"))
        self.excel.setText(_translate("InventoryForm", "Excel"))
from clipview import ClipLineEdit, ClipView
import icons_rc
