# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\invoice_expenses_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(980, 452)
        self.partial = QtWidgets.QGroupBox(Form)
        self.partial.setGeometry(QtCore.QRect(60, 130, 851, 241))
        self.partial.setCheckable(False)
        self.partial.setChecked(False)
        self.partial.setObjectName("partial")
        self.view = QtWidgets.QTableView(self.partial)
        self.view.setGeometry(QtCore.QRect(0, 20, 851, 220))
        self.view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.view.setObjectName("view")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(700, 400, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(60, 40, 851, 81))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(40, 30, 730, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.date = QtWidgets.QLineEdit(self.widget)
        self.date.setMinimumSize(QtCore.QSize(81, 22))
        self.date.setMaximumSize(QtCore.QSize(81, 22))
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.horizontalLayout.addWidget(self.date)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.amount = QtWidgets.QLineEdit(self.widget)
        self.amount.setAlignment(QtCore.Qt.AlignCenter)
        self.amount.setObjectName("amount")
        self.horizontalLayout.addWidget(self.amount)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.info = QtWidgets.QLineEdit(self.widget)
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.horizontalLayout.addWidget(self.info)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.proforma = QtWidgets.QLineEdit(self.widget)
        self.proforma.setAlignment(QtCore.Qt.AlignCenter)
        self.proforma.setObjectName("proforma")
        self.horizontalLayout.addWidget(self.proforma)
        self.add = QtWidgets.QToolButton(self.widget)
        self.add.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        self.add.setIconSize(QtCore.QSize(24, 24))
        self.add.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.add.setAutoRaise(True)
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.accept)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Invoice Expense"))
        self.partial.setTitle(_translate("Form", "Expenses:"))
        self.pushButton.setText(_translate("Form", "Exit"))
        self.groupBox.setTitle(_translate("Form", "Add Expense:"))
        self.label.setText(_translate("Form", "Date:"))
        self.date.setPlaceholderText(_translate("Form", "ddmmyyyy"))
        self.label_6.setText(_translate("Form", "Amount:"))
        self.label_7.setText(_translate("Form", "Info:"))
        self.label_2.setText(_translate("Form", "Proforma:"))
        self.add.setText(_translate("Form", "Add"))
import icons_rc
