# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\line_complete_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineCompleteForm(object):
    def setupUi(self, LineCompleteForm):
        LineCompleteForm.setObjectName("LineCompleteForm")
        LineCompleteForm.resize(391, 331)
        self.ok = QtWidgets.QPushButton(LineCompleteForm)
        self.ok.setGeometry(QtCore.QRect(160, 280, 93, 28))
        self.ok.setDefault(True)
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(LineCompleteForm)
        self.cancel.setGeometry(QtCore.QRect(270, 280, 93, 28))
        self.cancel.setObjectName("cancel")
        self.label = QtWidgets.QLabel(LineCompleteForm)
        self.label.setGeometry(QtCore.QRect(131, 41, 21, 16))
        self.label.setObjectName("label")
        self.qnt = QtWidgets.QSpinBox(LineCompleteForm)
        self.qnt.setGeometry(QtCore.QRect(159, 41, 121, 20))
        self.qnt.setMinimum(1)
        self.qnt.setMaximum(10000)
        self.qnt.setObjectName("qnt")
        self.label_2 = QtWidgets.QLabel(LineCompleteForm)
        self.label_2.setGeometry(QtCore.QRect(61, 74, 91, 16))
        self.label_2.setObjectName("label_2")
        self.condition = QtWidgets.QLineEdit(LineCompleteForm)
        self.condition.setGeometry(QtCore.QRect(159, 74, 120, 20))
        self.condition.setObjectName("condition")
        self.label_3 = QtWidgets.QLabel(LineCompleteForm)
        self.label_3.setGeometry(QtCore.QRect(107, 111, 44, 16))
        self.label_3.setObjectName("label_3")
        self.price = QtWidgets.QDoubleSpinBox(LineCompleteForm)
        self.price.setGeometry(QtCore.QRect(158, 111, 121, 20))
        self.price.setMinimum(1.0)
        self.price.setMaximum(10000000.0)
        self.price.setObjectName("price")
        self.ignore_spec = QtWidgets.QCheckBox(LineCompleteForm)
        self.ignore_spec.setGeometry(QtCore.QRect(160, 190, 131, 20))
        self.ignore_spec.setChecked(True)
        self.ignore_spec.setObjectName("ignore_spec")
        self.label_4 = QtWidgets.QLabel(LineCompleteForm)
        self.label_4.setGeometry(QtCore.QRect(130, 150, 31, 16))
        self.label_4.setObjectName("label_4")
        self.tax = QtWidgets.QComboBox(LineCompleteForm)
        self.tax.setGeometry(QtCore.QRect(160, 150, 121, 22))
        self.tax.setObjectName("tax")
        self.tax.addItem("")
        self.tax.addItem("")
        self.tax.addItem("")
        self.tax.addItem("")

        self.retranslateUi(LineCompleteForm)
        self.tax.setCurrentIndex(3)
        self.ok.clicked.connect(LineCompleteForm.accept)
        self.cancel.clicked.connect(LineCompleteForm.reject)
        QtCore.QMetaObject.connectSlotsByName(LineCompleteForm)

    def retranslateUi(self, LineCompleteForm):
        _translate = QtCore.QCoreApplication.translate
        LineCompleteForm.setWindowTitle(_translate("LineCompleteForm", "Dialog"))
        self.ok.setText(_translate("LineCompleteForm", "Ok"))
        self.cancel.setText(_translate("LineCompleteForm", "Cancel"))
        self.label.setText(_translate("LineCompleteForm", "Qnt:"))
        self.label_2.setText(_translate("LineCompleteForm", "Showing Condition:"))
        self.label_3.setText(_translate("LineCompleteForm", "Unit/Price"))
        self.ignore_spec.setText(_translate("LineCompleteForm", "Ignore spec in Invoice"))
        self.label_4.setText(_translate("LineCompleteForm", "Tax:"))
        self.tax.setItemText(0, _translate("LineCompleteForm", "0"))
        self.tax.setItemText(1, _translate("LineCompleteForm", "4"))
        self.tax.setItemText(2, _translate("LineCompleteForm", "10"))
        self.tax.setItemText(3, _translate("LineCompleteForm", "21"))
