# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\output.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1381, 730)
        self.view = QtWidgets.QTableView(Dialog)
        self.view.setGeometry(QtCore.QRect(60, 40, 1291, 591))
        self.view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.view.setObjectName("view")
        self._export = QtWidgets.QToolButton(Dialog)
        self._export.setGeometry(QtCore.QRect(1100, 650, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self._export.setFont(font)
        self._export.setStyleSheet("background:lightgray; ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/excel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._export.setIcon(icon)
        self._export.setIconSize(QtCore.QSize(50, 50))
        self._export.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self._export.setObjectName("_export")
        self.exit = QtWidgets.QPushButton(Dialog)
        self.exit.setGeometry(QtCore.QRect(1240, 650, 120, 60))
        self.exit.setStyleSheet("background:lightgray; ")
        self.exit.setObjectName("exit")

        self.retranslateUi(Dialog)
        self.exit.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self._export.setText(_translate("Dialog", "Export"))
        self.exit.setText(_translate("Dialog", "Exit"))
import icons_rc
