# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\quantity_price_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuantityPriceForm(object):
    def setupUi(self, QuantityPriceForm):
        QuantityPriceForm.setObjectName("QuantityPriceForm")
        QuantityPriceForm.resize(403, 183)
        QuantityPriceForm.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(QuantityPriceForm)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 60, 135, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.quantity = QtWidgets.QSpinBox(self.layoutWidget)
        self.quantity.setMinimum(1)
        self.quantity.setMaximum(10000)
        self.quantity.setObjectName("quantity")
        self.horizontalLayout.addWidget(self.quantity)
        self.layoutWidget1 = QtWidgets.QWidget(QuantityPriceForm)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 60, 135, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.price = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.price.setMinimum(1.0)
        self.price.setMaximum(9999999.0)
        self.price.setObjectName("price")
        self.horizontalLayout_2.addWidget(self.price)
        self.ok = QtWidgets.QPushButton(QuantityPriceForm)
        self.ok.setGeometry(QtCore.QRect(150, 130, 93, 28))
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(QuantityPriceForm)
        self.cancel.setGeometry(QtCore.QRect(280, 130, 93, 28))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(QuantityPriceForm)
        self.cancel.clicked.connect(QuantityPriceForm.close)
        self.ok.clicked.connect(QuantityPriceForm.accept)
        QtCore.QMetaObject.connectSlotsByName(QuantityPriceForm)

    def retranslateUi(self, QuantityPriceForm):
        _translate = QtCore.QCoreApplication.translate
        QuantityPriceForm.setWindowTitle(_translate("QuantityPriceForm", "Dialog"))
        self.label_2.setText(_translate("QuantityPriceForm", "Quantity:"))
        self.label_3.setText(_translate("QuantityPriceForm", "Price:"))
        self.ok.setText(_translate("QuantityPriceForm", "Ok"))
        self.cancel.setText(_translate("QuantityPriceForm", "Cancel"))
