# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\rmas_incoming_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1602, 786)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/euromedia"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.save = QtWidgets.QToolButton(Form)
        self.save.setGeometry(QtCore.QRect(1400, 690, 81, 61))
        self.save.setStyleSheet("background:lightgray; ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon1)
        self.save.setIconSize(QtCore.QSize(24, 24))
        self.save.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.save.setAutoRaise(True)
        self.save.setObjectName("save")
        self.exit = QtWidgets.QToolButton(Form)
        self.exit.setGeometry(QtCore.QRect(1500, 690, 71, 61))
        self.exit.setStyleSheet("background:lightgray; ")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon2)
        self.exit.setIconSize(QtCore.QSize(24, 24))
        self.exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exit.setAutoRaise(True)
        self.exit.setObjectName("exit")
        self.view = QtWidgets.QTableView(Form)
        self.view.setGeometry(QtCore.QRect(30, 60, 1541, 531))
        self.view.setObjectName("view")
        self.sn = QtWidgets.QLineEdit(Form)
        self.sn.setGeometry(QtCore.QRect(648, 19, 271, 20))
        self.sn.setObjectName("sn")
        self.check = QtWidgets.QPushButton(Form)
        self.check.setGeometry(QtCore.QRect(938, 14, 81, 31))
        self.check.setAutoDefault(True)
        self.check.setDefault(True)
        self.check.setObjectName("check")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(580, 20, 51, 21))
        self.label_3.setObjectName("label_3")
        self.delete_ = QtWidgets.QPushButton(Form)
        self.delete_.setGeometry(QtCore.QRect(1500, 600, 75, 31))
        self.delete_.setObjectName("delete_")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(100, 25, 47, 13))
        self.label_4.setObjectName("label_4")
        self.date = QtWidgets.QLineEdit(Form)
        self.date.setGeometry(QtCore.QRect(150, 20, 151, 20))
        self.date.setReadOnly(True)
        self.date.setObjectName("date")

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Incoming Rmas"))
        self.save.setText(_translate("Form", "SAVE"))
        self.exit.setText(_translate("Form", "EXIT"))
        self.check.setText(_translate("Form", "Check"))
        self.label_3.setText(_translate("Form", "IMEI/SN:"))
        self.delete_.setText(_translate("Form", "Delete"))
        self.label_4.setText(_translate("Form", "Date:"))
import icons_rc
