# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\rmas_incoming_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1298, 861)
        self.partner = QtWidgets.QLineEdit(Form)
        self.partner.setGeometry(QtCore.QRect(360, 60, 271, 20))
        self.partner.setObjectName("partner")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(310, 60, 61, 20))
        self.label.setObjectName("label")
        self.save = QtWidgets.QToolButton(Form)
        self.save.setGeometry(QtCore.QRect(1100, 770, 81, 61))
        self.save.setStyleSheet("background:lightgray; ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon)
        self.save.setIconSize(QtCore.QSize(24, 24))
        self.save.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.save.setAutoRaise(True)
        self.save.setObjectName("save")
        self.exit = QtWidgets.QToolButton(Form)
        self.exit.setGeometry(QtCore.QRect(1200, 770, 71, 61))
        self.exit.setStyleSheet("background:lightgray; ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon1)
        self.exit.setIconSize(QtCore.QSize(24, 24))
        self.exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exit.setAutoRaise(True)
        self.exit.setObjectName("exit")
        self.view = QtWidgets.QTableView(Form)
        self.view.setGeometry(QtCore.QRect(40, 230, 1231, 461))
        self.view.setObjectName("view")
        self.sn = QtWidgets.QLineEdit(Form)
        self.sn.setGeometry(QtCore.QRect(340, 165, 271, 20))
        self.sn.setObjectName("sn")
        self.check = QtWidgets.QPushButton(Form)
        self.check.setGeometry(QtCore.QRect(630, 160, 81, 31))
        self.check.setAutoDefault(False)
        self.check.setDefault(True)
        self.check.setObjectName("check")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(272, 166, 51, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1190, 700, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 65, 47, 13))
        self.label_4.setObjectName("label_4")
        self.date = QtWidgets.QLineEdit(Form)
        self.date.setGeometry(QtCore.QRect(110, 60, 151, 20))
        self.date.setObjectName("date")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(710, 60, 191, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.warranty = QtWidgets.QLineEdit(self.layoutWidget)
        self.warranty.setReadOnly(True)
        self.warranty.setObjectName("warranty")
        self.horizontalLayout.addWidget(self.warranty)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "INCOMING RMAS"))
        self.label.setText(_translate("Form", "Partner:"))
        self.save.setText(_translate("Form", "SAVE"))
        self.exit.setText(_translate("Form", "EXIT"))
        self.check.setText(_translate("Form", "Check"))
        self.label_3.setText(_translate("Form", "IMEI/SN:"))
        self.pushButton_2.setText(_translate("Form", "Delete"))
        self.label_4.setText(_translate("Form", "Date:"))
        self.label_2.setText(_translate("Form", "Warranty:"))
import icons_rc
