# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\switch_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(398, 315)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 361, 221))
        self.groupBox.setObjectName("groupBox")
        self.view = QtWidgets.QListView(self.groupBox)
        self.view.setGeometry(QtCore.QRect(0, 20, 361, 201))
        self.view.setAlternatingRowColors(True)
        self.view.setObjectName("view")
        self.switch_ = QtWidgets.QPushButton(Dialog)
        self.switch_.setGeometry(QtCore.QRect(224, 255, 75, 23))
        self.switch_.setObjectName("switch_")
        self.exit = QtWidgets.QPushButton(Dialog)
        self.exit.setGeometry(QtCore.QRect(304, 255, 75, 23))
        self.exit.setObjectName("exit")

        self.retranslateUi(Dialog)
        self.exit.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Switch Company"))
        self.groupBox.setTitle(_translate("Dialog", "Companies:"))
        self.switch_.setText(_translate("Dialog", "Switch"))
        self.exit.setText(_translate("Dialog", "Exit"))
