# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\spec_change_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpecChange(object):
    def setupUi(self, SpecChange):
        SpecChange.setObjectName("SpecChange")
        SpecChange.resize(485, 341)
        self.label_3 = QtWidgets.QLabel(SpecChange)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 91, 20))
        self.label_3.setObjectName("label_3")
        self.current_spec = QtWidgets.QLineEdit(SpecChange)
        self.current_spec.setGeometry(QtCore.QRect(140, 150, 161, 22))
        self.current_spec.setReadOnly(True)
        self.current_spec.setObjectName("current_spec")
        self.label_4 = QtWidgets.QLabel(SpecChange)
        self.label_4.setGeometry(QtCore.QRect(60, 210, 71, 16))
        self.label_4.setObjectName("label_4")
        self.new_spec = QtWidgets.QLineEdit(SpecChange)
        self.new_spec.setGeometry(QtCore.QRect(140, 210, 161, 22))
        self.new_spec.setReadOnly(False)
        self.new_spec.setObjectName("new_spec")
        self.exit = QtWidgets.QPushButton(SpecChange)
        self.exit.setGeometry(QtCore.QRect(330, 290, 101, 28))
        self.exit.setObjectName("exit")
        self.update = QtWidgets.QPushButton(SpecChange)
        self.update.setGeometry(QtCore.QRect(330, 210, 101, 28))
        self.update.setObjectName("update")
        self.widget = QtWidgets.QWidget(SpecChange)
        self.widget.setGeometry(QtCore.QRect(60, 30, 321, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sn = QtWidgets.QLineEdit(self.widget)
        self.sn.setMinimumSize(QtCore.QSize(261, 22))
        self.sn.setMaximumSize(QtCore.QSize(261, 22))
        self.sn.setAlignment(QtCore.Qt.AlignCenter)
        self.sn.setObjectName("sn")
        self.horizontalLayout.addWidget(self.sn)
        self.widget1 = QtWidgets.QWidget(SpecChange)
        self.widget1.setGeometry(QtCore.QRect(50, 80, 338, 24))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.description = QtWidgets.QLineEdit(self.widget1)
        self.description.setMinimumSize(QtCore.QSize(261, 22))
        self.description.setMaximumSize(QtCore.QSize(261, 22))
        self.description.setReadOnly(True)
        self.description.setObjectName("description")
        self.horizontalLayout_2.addWidget(self.description)

        self.retranslateUi(SpecChange)
        QtCore.QMetaObject.connectSlotsByName(SpecChange)

    def retranslateUi(self, SpecChange):
        _translate = QtCore.QCoreApplication.translate
        SpecChange.setWindowTitle(_translate("SpecChange", "SpecChange"))
        self.label_3.setText(_translate("SpecChange", "Current Spec:"))
        self.label_4.setText(_translate("SpecChange", "New Spec:"))
        self.exit.setText(_translate("SpecChange", "Exit"))
        self.update.setText(_translate("SpecChange", "Update"))
        self.label.setText(_translate("SpecChange", "IMEI/SN:"))
        self.sn.setPlaceholderText(_translate("SpecChange", "Press enter to search .. "))
        self.label_2.setText(_translate("SpecChange", "Description:"))
import icons_rc
