# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\spec.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpecForm(object):
    def setupUi(self, SpecForm):
        SpecForm.setObjectName("SpecForm")
        SpecForm.resize(461, 322)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warehouse"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SpecForm.setWindowIcon(icon)
        self.view = QtWidgets.QListView(SpecForm)
        self.view.setGeometry(QtCore.QRect(50, 60, 261, 211))
        self.view.setObjectName("view")
        self.add = QtWidgets.QPushButton(SpecForm)
        self.add.setGeometry(QtCore.QRect(330, 30, 93, 21))
        self.add.setObjectName("add")
        self.delete_2 = QtWidgets.QPushButton(SpecForm)
        self.delete_2.setGeometry(QtCore.QRect(330, 200, 93, 28))
        self.delete_2.setObjectName("delete_2")
        self.exit = QtWidgets.QPushButton(SpecForm)
        self.exit.setGeometry(QtCore.QRect(330, 240, 93, 28))
        self.exit.setObjectName("exit")
        self.input = QtWidgets.QLineEdit(SpecForm)
        self.input.setGeometry(QtCore.QRect(50, 30, 261, 22))
        self.input.setObjectName("input")

        self.retranslateUi(SpecForm)
        self.exit.clicked.connect(SpecForm.close)
        QtCore.QMetaObject.connectSlotsByName(SpecForm)

    def retranslateUi(self, SpecForm):
        _translate = QtCore.QCoreApplication.translate
        SpecForm.setWindowTitle(_translate("SpecForm", "Specs"))
        self.add.setText(_translate("SpecForm", "Add"))
        self.delete_2.setText(_translate("SpecForm", "Delete"))
        self.exit.setText(_translate("SpecForm", "Exit"))
import icons_rc
