# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\trace_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1392, 604)
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(1300, 558, 78, 30))
        self.exit.setAutoDefault(False)
        self.exit.setObjectName("exit")
        self.search_button = QtWidgets.QPushButton(Form)
        self.search_button.setGeometry(QtCore.QRect(344, 30, 78, 30))
        self.search_button.setAutoDefault(False)
        self.search_button.setDefault(True)
        self.search_button.setObjectName("search_button")
        self.wh_view = QtWidgets.QTableView(Form)
        self.wh_view.setGeometry(QtCore.QRect(10, 380, 450, 150))
        self.wh_view.setObjectName("wh_view")
        self.condition_view = QtWidgets.QTableView(Form)
        self.condition_view.setGeometry(QtCore.QRect(470, 380, 450, 150))
        self.condition_view.setObjectName("condition_view")
        self.spec_view = QtWidgets.QTableView(Form)
        self.spec_view.setGeometry(QtCore.QRect(930, 380, 450, 150))
        self.spec_view.setObjectName("spec_view")
        self.trace_view = QtWidgets.QTableView(Form)
        self.trace_view.setGeometry(QtCore.QRect(10, 112, 1371, 241))
        self.trace_view.setObjectName("trace_view")
        self.sn = ClipLineEdit(Form)
        self.sn.setGeometry(QtCore.QRect(30, 35, 300, 20))
        self.sn.setInputMask("")
        self.sn.setText("")
        self.sn.setPlaceholderText("")
        self.sn.setClearButtonEnabled(False)
        self.sn.setObjectName("sn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 360, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(470, 360, 120, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(930, 360, 120, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 92, 191, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 65, 65, 25))
        self.label_5.setObjectName("label_5")
        self.last_description = QtWidgets.QLabel(Form)
        self.last_description.setGeometry(QtCore.QRect(100, 65, 600, 25))
        self.last_description.setText("")
        self.last_description.setObjectName("last_description")

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dialog"))
        self.exit.setText(_translate("Form", "Exit"))
        self.search_button.setText(_translate("Form", "Search"))
        self.label.setText(_translate("Form", "Warehouse Changes:"))
        self.label_2.setText(_translate("Form", "Condition Changes:"))
        self.label_3.setText(_translate("Form", "Spec Changes:"))
        self.label_4.setText(_translate("Form", "Purchased/Sold/Returned on:"))
        self.label_5.setText(_translate("Form", "Description:"))
from clipview import ClipLineEdit
