# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\warehouse_change_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarehouseChange(object):
    def setupUi(self, WarehouseChange):
        WarehouseChange.setObjectName("WarehouseChange")
        WarehouseChange.resize(591, 404)
        self.label = QtWidgets.QLabel(WarehouseChange)
        self.label.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(WarehouseChange)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 71, 16))
        self.label_2.setObjectName("label_2")
        self.sn = QtWidgets.QLineEdit(WarehouseChange)
        self.sn.setGeometry(QtCore.QRect(152, 40, 311, 22))
        self.sn.setAlignment(QtCore.Qt.AlignCenter)
        self.sn.setObjectName("sn")
        self.description = QtWidgets.QLineEdit(WarehouseChange)
        self.description.setGeometry(QtCore.QRect(152, 90, 311, 22))
        self.description.setReadOnly(True)
        self.description.setObjectName("description")
        self.label_3 = QtWidgets.QLabel(WarehouseChange)
        self.label_3.setGeometry(QtCore.QRect(60, 190, 131, 16))
        self.label_3.setObjectName("label_3")
        self.current_warehouse = QtWidgets.QLineEdit(WarehouseChange)
        self.current_warehouse.setGeometry(QtCore.QRect(190, 190, 211, 22))
        self.current_warehouse.setReadOnly(True)
        self.current_warehouse.setObjectName("current_warehouse")
        self.label_4 = QtWidgets.QLabel(WarehouseChange)
        self.label_4.setGeometry(QtCore.QRect(70, 240, 111, 20))
        self.label_4.setObjectName("label_4")
        self.new_warehouse = QtWidgets.QComboBox(WarehouseChange)
        self.new_warehouse.setGeometry(QtCore.QRect(190, 240, 201, 22))
        self.new_warehouse.setEditable(False)
        self.new_warehouse.setObjectName("new_warehouse")
        self.update = QtWidgets.QPushButton(WarehouseChange)
        self.update.setGeometry(QtCore.QRect(450, 240, 93, 28))
        self.update.setObjectName("update")
        self.exit = QtWidgets.QPushButton(WarehouseChange)
        self.exit.setGeometry(QtCore.QRect(450, 340, 93, 28))
        self.exit.setObjectName("exit")

        self.retranslateUi(WarehouseChange)
        QtCore.QMetaObject.connectSlotsByName(WarehouseChange)

    def retranslateUi(self, WarehouseChange):
        _translate = QtCore.QCoreApplication.translate
        WarehouseChange.setWindowTitle(_translate("WarehouseChange", "Dialog"))
        self.label.setText(_translate("WarehouseChange", "IMEI/SN:"))
        self.label_2.setText(_translate("WarehouseChange", "Description:"))
        self.sn.setPlaceholderText(_translate("WarehouseChange", "Enter SN or Imei and press Enter ..."))
        self.label_3.setText(_translate("WarehouseChange", "Current Warehouse:"))
        self.label_4.setText(_translate("WarehouseChange", "New Warehouse:"))
        self.update.setText(_translate("WarehouseChange", "Update"))
        self.exit.setText(_translate("WarehouseChange", "Exit"))
