# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\warehouse_rma_incoming_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(951, 596)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rmas"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 47, 13))
        self.label.setObjectName("label")
        self.date = QtWidgets.QLineEdit(Form)
        self.date.setGeometry(QtCore.QRect(100, 47, 131, 20))
        self.date.setReadOnly(True)
        self.date.setObjectName("date")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.partner = QtWidgets.QLineEdit(Form)
        self.partner.setGeometry(QtCore.QRect(350, 47, 311, 20))
        self.partner.setReadOnly(True)
        self.partner.setObjectName("partner")
        self.view = QtWidgets.QTableView(Form)
        self.view.setGeometry(QtCore.QRect(40, 120, 881, 331))
        self.view.setObjectName("view")
        self.save = QtWidgets.QToolButton(Form)
        self.save.setGeometry(QtCore.QRect(780, 510, 70, 60))
        self.save.setMinimumSize(QtCore.QSize(70, 60))
        self.save.setMaximumSize(QtCore.QSize(70, 60))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon1)
        self.save.setIconSize(QtCore.QSize(40, 40))
        self.save.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.save.setAutoRaise(True)
        self.save.setObjectName("save")
        self.exit = QtWidgets.QToolButton(Form)
        self.exit.setGeometry(QtCore.QRect(870, 510, 70, 60))
        self.exit.setMinimumSize(QtCore.QSize(70, 60))
        self.exit.setMaximumSize(QtCore.QSize(70, 60))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon2)
        self.exit.setIconSize(QtCore.QSize(40, 40))
        self.exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exit.setAutoRaise(True)
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Rma physical check"))
        self.label.setText(_translate("Form", "Date:"))
        self.label_2.setText(_translate("Form", "Partner:"))
        self.save.setText(_translate("Form", "Save"))
        self.exit.setText(_translate("Form", "Exit"))
import icons_rc
