# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\warehouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarehouseForm(object):
    def setupUi(self, WarehouseForm):
        WarehouseForm.setObjectName("WarehouseForm")
        WarehouseForm.resize(461, 322)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warehouse"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WarehouseForm.setWindowIcon(icon)
        self.view = QtWidgets.QListView(WarehouseForm)
        self.view.setGeometry(QtCore.QRect(50, 60, 261, 211))
        self.view.setObjectName("view")
        self.add = QtWidgets.QPushButton(WarehouseForm)
        self.add.setGeometry(QtCore.QRect(330, 30, 93, 21))
        self.add.setObjectName("add")
        self.delete_2 = QtWidgets.QPushButton(WarehouseForm)
        self.delete_2.setGeometry(QtCore.QRect(330, 200, 93, 28))
        self.delete_2.setObjectName("delete_2")
        self.exit = QtWidgets.QPushButton(WarehouseForm)
        self.exit.setGeometry(QtCore.QRect(330, 240, 93, 28))
        self.exit.setObjectName("exit")
        self.input = QtWidgets.QLineEdit(WarehouseForm)
        self.input.setGeometry(QtCore.QRect(50, 30, 261, 22))
        self.input.setObjectName("input")

        self.retranslateUi(WarehouseForm)
        QtCore.QMetaObject.connectSlotsByName(WarehouseForm)

    def retranslateUi(self, WarehouseForm):
        _translate = QtCore.QCoreApplication.translate
        WarehouseForm.setWindowTitle(_translate("WarehouseForm", "Warehouses"))
        self.add.setText(_translate("WarehouseForm", "Add"))
        self.delete_2.setText(_translate("WarehouseForm", "Delete"))
        self.exit.setText(_translate("WarehouseForm", "Exit"))
import icons_rc
