# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\window_inputs_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(579, 272)
        self.end = QtWidgets.QLineEdit(Dialog)
        self.end.setGeometry(QtCore.QRect(170, 90, 321, 20))
        self.end.setAlignment(QtCore.Qt.AlignCenter)
        self.end.setReadOnly(True)
        self.end.setObjectName("end")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(49, 90, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 71, 21))
        self.label_2.setObjectName("label_2")
        self.rate = QtWidgets.QLineEdit(Dialog)
        self.rate.setGeometry(QtCore.QRect(170, 130, 321, 20))
        self.rate.setText("")
        self.rate.setAlignment(QtCore.Qt.AlignCenter)
        self.rate.setObjectName("rate")
        self.run = QtWidgets.QPushButton(Dialog)
        self.run.setGeometry(QtCore.QRect(260, 170, 101, 31))
        self.run.setAutoDefault(False)
        self.run.setDefault(False)
        self.run.setObjectName("run")
        self.exit = QtWidgets.QToolButton(Dialog)
        self.exit.setGeometry(QtCore.QRect(430, 190, 61, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background:lightgray; ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon)
        self.exit.setIconSize(QtCore.QSize(50, 50))
        self.exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exit.setObjectName("exit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 50, 91, 16))
        self.label_3.setObjectName("label_3")
        self.start = QtWidgets.QLineEdit(Dialog)
        self.start.setGeometry(QtCore.QRect(170, 50, 321, 20))
        self.start.setText("")
        self.start.setAlignment(QtCore.Qt.AlignCenter)
        self.start.setObjectName("start")

        self.retranslateUi(Dialog)
        self.exit.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change Description"))
        self.end.setPlaceholderText(_translate("Dialog", "Date in format: ddmmyyyy"))
        self.label.setText(_translate("Dialog", "End Date:"))
        self.label_2.setText(_translate("Dialog", "Default Rate:"))
        self.rate.setPlaceholderText(_translate("Dialog", "1.2"))
        self.run.setText(_translate("Dialog", "Run report"))
        self.exit.setText(_translate("Dialog", "Exit"))
        self.label_3.setText(_translate("Dialog", "Start Date:"))
        self.start.setPlaceholderText(_translate("Dialog", "Date in format: ddmmyyyy"))
import icons_rc
